// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ItemCardType.
const (
	ItemCardTypeArticle ItemCardType = "article"
	ItemCardTypeBook    ItemCardType = "book"
	ItemCardTypeImage   ItemCardType = "image"
	ItemCardTypeNote    ItemCardType = "note"
	ItemCardTypeProduct ItemCardType = "product"
	ItemCardTypeQuote   ItemCardType = "quote"
	ItemCardTypeRecipe  ItemCardType = "recipe"
	ItemCardTypeTweet   ItemCardType = "tweet"
	ItemCardTypeVideo   ItemCardType = "video"
)

// Defines values for ItemStatus.
const (
	ItemStatusEnriched ItemStatus = "enriched"
	ItemStatusFailed   ItemStatus = "failed"
	ItemStatusPending  ItemStatus = "pending"
)

// Defines values for ItemDetailCardType.
const (
	ItemDetailCardTypeArticle ItemDetailCardType = "article"
	ItemDetailCardTypeBook    ItemDetailCardType = "book"
	ItemDetailCardTypeImage   ItemDetailCardType = "image"
	ItemDetailCardTypeNote    ItemDetailCardType = "note"
	ItemDetailCardTypeProduct ItemDetailCardType = "product"
	ItemDetailCardTypeQuote   ItemDetailCardType = "quote"
	ItemDetailCardTypeRecipe  ItemDetailCardType = "recipe"
	ItemDetailCardTypeTweet   ItemDetailCardType = "tweet"
	ItemDetailCardTypeVideo   ItemDetailCardType = "video"
)

// Defines values for ItemDetailStatus.
const (
	ItemDetailStatusEnriched ItemDetailStatus = "enriched"
	ItemDetailStatusFailed   ItemDetailStatus = "failed"
	ItemDetailStatusPending  ItemDetailStatus = "pending"
)

// Defines values for LensRuleTypes.
const (
	LensRuleTypesArticle LensRuleTypes = "article"
	LensRuleTypesBook    LensRuleTypes = "book"
	LensRuleTypesImage   LensRuleTypes = "image"
	LensRuleTypesNote    LensRuleTypes = "note"
	LensRuleTypesProduct LensRuleTypes = "product"
	LensRuleTypesQuote   LensRuleTypes = "quote"
	LensRuleTypesRecipe  LensRuleTypes = "recipe"
	LensRuleTypesTweet   LensRuleTypes = "tweet"
	LensRuleTypesVideo   LensRuleTypes = "video"
)

// Defines values for PatchSettingsRequestNotifyDigest.
const (
	PatchSettingsRequestNotifyDigestBoth  PatchSettingsRequestNotifyDigest = "both"
	PatchSettingsRequestNotifyDigestEmail PatchSettingsRequestNotifyDigest = "email"
	PatchSettingsRequestNotifyDigestOff   PatchSettingsRequestNotifyDigest = "off"
	PatchSettingsRequestNotifyDigestPush  PatchSettingsRequestNotifyDigest = "push"
)

// Defines values for PatchSettingsRequestNotifyFeedRiver.
const (
	PatchSettingsRequestNotifyFeedRiverBoth  PatchSettingsRequestNotifyFeedRiver = "both"
	PatchSettingsRequestNotifyFeedRiverEmail PatchSettingsRequestNotifyFeedRiver = "email"
	PatchSettingsRequestNotifyFeedRiverOff   PatchSettingsRequestNotifyFeedRiver = "off"
	PatchSettingsRequestNotifyFeedRiverPush  PatchSettingsRequestNotifyFeedRiver = "push"
)

// Defines values for PatchSettingsRequestNotifyLifecycle.
const (
	PatchSettingsRequestNotifyLifecycleBoth  PatchSettingsRequestNotifyLifecycle = "both"
	PatchSettingsRequestNotifyLifecycleEmail PatchSettingsRequestNotifyLifecycle = "email"
	PatchSettingsRequestNotifyLifecycleOff   PatchSettingsRequestNotifyLifecycle = "off"
	PatchSettingsRequestNotifyLifecyclePush  PatchSettingsRequestNotifyLifecycle = "push"
)

// Defines values for RegisterPushDeviceRequestPlatform.
const (
	Android RegisterPushDeviceRequestPlatform = "android"
	Ios     RegisterPushDeviceRequestPlatform = "ios"
)

// Defines values for SettingsNotifyDigest.
const (
	SettingsNotifyDigestBoth  SettingsNotifyDigest = "both"
	SettingsNotifyDigestEmail SettingsNotifyDigest = "email"
	SettingsNotifyDigestOff   SettingsNotifyDigest = "off"
	SettingsNotifyDigestPush  SettingsNotifyDigest = "push"
)

// Defines values for SettingsNotifyFeedRiver.
const (
	SettingsNotifyFeedRiverBoth  SettingsNotifyFeedRiver = "both"
	SettingsNotifyFeedRiverEmail SettingsNotifyFeedRiver = "email"
	SettingsNotifyFeedRiverOff   SettingsNotifyFeedRiver = "off"
	SettingsNotifyFeedRiverPush  SettingsNotifyFeedRiver = "push"
)

// Defines values for SettingsNotifyLifecycle.
const (
	SettingsNotifyLifecycleBoth  SettingsNotifyLifecycle = "both"
	SettingsNotifyLifecycleEmail SettingsNotifyLifecycle = "email"
	SettingsNotifyLifecycleOff   SettingsNotifyLifecycle = "off"
	SettingsNotifyLifecyclePush  SettingsNotifyLifecycle = "push"
)

// Defines values for UnderstoodQueryTypes.
const (
	UnderstoodQueryTypesArticle UnderstoodQueryTypes = "article"
	UnderstoodQueryTypesBook    UnderstoodQueryTypes = "book"
	UnderstoodQueryTypesImage   UnderstoodQueryTypes = "image"
	UnderstoodQueryTypesNote    UnderstoodQueryTypes = "note"
	UnderstoodQueryTypesProduct UnderstoodQueryTypes = "product"
	UnderstoodQueryTypesQuote   UnderstoodQueryTypes = "quote"
	UnderstoodQueryTypesRecipe  UnderstoodQueryTypes = "recipe"
	UnderstoodQueryTypesTweet   UnderstoodQueryTypes = "tweet"
	UnderstoodQueryTypesVideo   UnderstoodQueryTypes = "video"
)

// Account defines model for Account.
type Account struct {
	// AssetBytes Total bytes of uploaded assets. There is no quota — self-hosting is unbounded — so this is usage, not a fraction of a limit.
	AssetBytes int64 `json:"assetBytes"`

	// Email The account's e-mail. Empty in single-user token mode, which has no identity provider — callers must render a neutral label rather than inventing one.
	Email *string `json:"email,omitempty"`

	// ItemCount Items the caller owns.
	ItemCount int64 `json:"itemCount"`
}

// ApiKey defines model for ApiKey.
type ApiKey struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`

	// LastUsedAt Absent until the key has authenticated a request.
	LastUsedAt *time.Time `json:"lastUsedAt,omitempty"`
	Name       string     `json:"name"`

	// Prefix Non-secret display prefix (e.g. omk_AbCd1234).
	Prefix string `json:"prefix"`

	// RevokedAt Absent unless the key has been revoked.
	RevokedAt *time.Time `json:"revokedAt,omitempty"`
}

// ApiKeyCreated defines model for ApiKeyCreated.
type ApiKeyCreated struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`

	// Key The full API key — shown exactly once.
	Key    string `json:"key"`
	Name   string `json:"name"`
	Prefix string `json:"prefix"`
}

// ClaimDeviceLinkRequest defines model for ClaimDeviceLinkRequest.
type ClaimDeviceLinkRequest struct {
	Code       string `json:"code"`
	DeviceName string `json:"deviceName"`
}

// CreateApiKeyRequest defines model for CreateApiKeyRequest.
type CreateApiKeyRequest struct {
	Name string `json:"name"`
}

// CreateDeviceLinkRequest defines model for CreateDeviceLinkRequest.
type CreateDeviceLinkRequest struct {
	DeviceHint *string `json:"deviceHint,omitempty"`
}

// CreateFeedRequest defines model for CreateFeedRequest.
type CreateFeedRequest struct {
	Url string `json:"url"`
}

// CreateHighlightRequest defines model for CreateHighlightRequest.
type CreateHighlightRequest struct {
	Exact      string  `json:"exact"`
	OffsetHint *int    `json:"offsetHint,omitempty"`
	Prefix     *string `json:"prefix,omitempty"`
	Suffix     *string `json:"suffix,omitempty"`
}

// CreateHighlightResponse defines model for CreateHighlightResponse.
type CreateHighlightResponse struct {
	Highlight Highlight `json:"highlight"`
	QuoteItem Item      `json:"quoteItem"`
}

// CreateItemRequest Exactly one of url or note must be provided.
type CreateItemRequest struct {
	Note *string `json:"note,omitempty"`
	Url  *string `json:"url,omitempty"`
}

// CreateLensRequest defines model for CreateLensRequest.
type CreateLensRequest struct {
	// DigestSchedule Optional cron-like digest schedule; omit or empty to leave digests disabled.
	DigestSchedule *string `json:"digestSchedule,omitempty"`
	Name           string  `json:"name"`

	// Rule A saved search rule. At least one of q, color, or types must be set. Applied like /search: q is text (FTS + vector), color ranks by palette proximity, types narrows by card type.
	Rule LensRule `json:"rule"`
}

// DeviceLinkClaimed defines model for DeviceLinkClaimed.
type DeviceLinkClaimed struct {
	// Key The full API key — shown exactly once.
	Key  string `json:"key"`
	Name string `json:"name"`
}

// DeviceLinkCreated defines model for DeviceLinkCreated.
type DeviceLinkCreated struct {
	// Code 8-character code formatted as ABCD-EFGH.
	Code      string    `json:"code"`
	ExpiresAt time.Time `json:"expiresAt"`
}

// DriftActionRequest defines model for DriftActionRequest.
type DriftActionRequest struct {
	// Keep Keep the item (pins it to the Desk); false lets it go.
	Keep bool `json:"keep"`
}

// DriftResponse defines model for DriftResponse.
type DriftResponse struct {
	Items []Item `json:"items"`

	// Total Total current drift candidates (for the 'n of total' line).
	Total int `json:"total"`
}

// Feed defines model for Feed.
type Feed struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`

	// LastPolledAt Absent until the feed has been polled at least once.
	LastPolledAt *time.Time `json:"lastPolledAt,omitempty"`

	// LastStatus 'ok' or 'error: …' from the most recent poll; empty before the first poll.
	LastStatus string `json:"lastStatus"`
	SiteUrl    string `json:"siteUrl"`
	Title      string `json:"title"`
	Url        string `json:"url"`
}

// Highlight defines model for Highlight.
type Highlight struct {
	CreatedAt    time.Time          `json:"createdAt"`
	Exact        string             `json:"exact"`
	Id           openapi_types.UUID `json:"id"`
	OffsetHint   int                `json:"offsetHint"`
	Prefix       string             `json:"prefix"`
	QuoteItemId  openapi_types.UUID `json:"quoteItemId"`
	SourceItemId openapi_types.UUID `json:"sourceItemId"`
	Suffix       string             `json:"suffix"`
}

// ImportResult Summary of a bulk import.
type ImportResult struct {
	// Failed Links rejected (not a valid http(s) URL) or that failed to save.
	Failed int `json:"failed"`

	// Imported New items created (and queued for enrichment).
	Imported int `json:"imported"`

	// Skipped Links skipped as already saved or duplicated within the file.
	Skipped int `json:"skipped"`

	// Total Links found in the file.
	Total int `json:"total"`
}

// Item defines model for Item.
type Item struct {
	CardType  *ItemCardType `json:"cardType,omitempty"`
	CreatedAt time.Time     `json:"createdAt"`

	// FeedId The feed this item originated from; null if not feed-sourced.
	FeedId *openapi_types.UUID `json:"feedId"`
	Id     openapi_types.UUID  `json:"id"`

	// KeptAt When the item was kept in the library from its feed; null if not kept.
	KeptAt       *time.Time `json:"keptAt"`
	LeadImageUrl *string    `json:"leadImageUrl,omitempty"`

	// PageCount Page count when the item's original is a stored PDF; null otherwise.
	PageCount *int      `json:"pageCount"`
	Palette   *[]string `json:"palette,omitempty"`

	// PinnedAt When the item was pinned to the Desk; null if not pinned.
	PinnedAt *time.Time `json:"pinnedAt"`
	Status   ItemStatus `json:"status"`
	Summary  *string    `json:"summary,omitempty"`
	Tags     *[]string  `json:"tags,omitempty"`
	Title    *string    `json:"title,omitempty"`
	Url      string     `json:"url"`
	UserTags *[]string  `json:"userTags,omitempty"`
}

// ItemCardType defines model for Item.CardType.
type ItemCardType string

// ItemStatus defines model for Item.Status.
type ItemStatus string

// ItemDetail defines model for ItemDetail.
type ItemDetail struct {
	Body      string              `json:"body"`
	CardType  *ItemDetailCardType `json:"cardType,omitempty"`
	CreatedAt time.Time           `json:"createdAt"`

	// FeedId The feed this item originated from; null if not feed-sourced.
	FeedId *openapi_types.UUID `json:"feedId"`
	Id     openapi_types.UUID  `json:"id"`

	// KeptAt When the item was kept in the library from its feed; null if not kept.
	KeptAt       *time.Time `json:"keptAt"`
	LeadImageUrl *string    `json:"leadImageUrl,omitempty"`

	// PageCount Page count when the item's original is a stored PDF; null otherwise.
	PageCount *int      `json:"pageCount"`
	Palette   *[]string `json:"palette,omitempty"`

	// PinnedAt When the item was pinned to the Desk; null if not pinned.
	PinnedAt *time.Time       `json:"pinnedAt"`
	Status   ItemDetailStatus `json:"status"`
	Summary  *string          `json:"summary,omitempty"`
	Tags     *[]string        `json:"tags,omitempty"`
	Title    *string          `json:"title,omitempty"`
	Url      string           `json:"url"`
	UserTags *[]string        `json:"userTags,omitempty"`
}

// ItemDetailCardType defines model for ItemDetail.CardType.
type ItemDetailCardType string

// ItemDetailStatus defines model for ItemDetail.Status.
type ItemDetailStatus string

// Lens defines model for Lens.
type Lens struct {
	CreatedAt time.Time `json:"createdAt"`

	// DigestSchedule Cron-like digest schedule string; empty means digests are disabled for this Lens.
	DigestSchedule string             `json:"digestSchedule"`
	Id             openapi_types.UUID `json:"id"`

	// LastDigestAt When this Lens last sent a digest; null if it never has.
	LastDigestAt *time.Time `json:"lastDigestAt"`
	Name         string     `json:"name"`

	// Rule A saved search rule. At least one of q, color, or types must be set. Applied like /search: q is text (FTS + vector), color ranks by palette proximity, types narrows by card type.
	Rule LensRule `json:"rule"`
}

// LensRule A saved search rule. At least one of q, color, or types must be set. Applied like /search: q is text (FTS + vector), color ranks by palette proximity, types narrows by card type.
type LensRule struct {
	// Color Hex (#RRGGBB) or named colour (e.g. cobalt).
	Color *string `json:"color,omitempty"`

	// Q Free-text query.
	Q *string `json:"q,omitempty"`

	// Types Card types to include.
	Types *[]LensRuleTypes `json:"types,omitempty"`
}

// LensRuleTypes defines model for LensRule.Types.
type LensRuleTypes string

// PatchSettingsRequest defines model for PatchSettingsRequest.
type PatchSettingsRequest struct {
	KindleEmail      *openapi_types.Email                 `json:"kindleEmail,omitempty"`
	NotifyDailyCap   *int                                 `json:"notifyDailyCap,omitempty"`
	NotifyDigest     *PatchSettingsRequestNotifyDigest    `json:"notifyDigest,omitempty"`
	NotifyFeedRiver  *PatchSettingsRequestNotifyFeedRiver `json:"notifyFeedRiver,omitempty"`
	NotifyLifecycle  *PatchSettingsRequestNotifyLifecycle `json:"notifyLifecycle,omitempty"`
	NotifyQuietHours *string                              `json:"notifyQuietHours,omitempty"`
	NotifyTimezone   *string                              `json:"notifyTimezone,omitempty"`
}

// PatchSettingsRequestNotifyDigest defines model for PatchSettingsRequest.NotifyDigest.
type PatchSettingsRequestNotifyDigest string

// PatchSettingsRequestNotifyFeedRiver defines model for PatchSettingsRequest.NotifyFeedRiver.
type PatchSettingsRequestNotifyFeedRiver string

// PatchSettingsRequestNotifyLifecycle defines model for PatchSettingsRequest.NotifyLifecycle.
type PatchSettingsRequestNotifyLifecycle string

// Place defines model for Place.
type Place struct {
	// Address geocoder display address; empty when not geocoded
	Address string `json:"address"`

	// Hint disambiguating locality from the source text, e.g. a city
	Hint string             `json:"hint"`
	Id   openapi_types.UUID `json:"id"`
	Lat  *float64           `json:"lat,omitempty"`
	Lng  *float64           `json:"lng,omitempty"`
	Name string             `json:"name"`

	// Source which signal produced this place (caption or vision)
	Source string `json:"source"`
}

// PlaceWithItem defines model for PlaceWithItem.
type PlaceWithItem struct {
	// Address geocoder display address; empty when not geocoded
	Address string `json:"address"`

	// Hint disambiguating locality from the source text, e.g. a city
	Hint         string             `json:"hint"`
	Id           openapi_types.UUID `json:"id"`
	ItemCardType string             `json:"itemCardType"`
	ItemId       openapi_types.UUID `json:"itemId"`
	ItemTitle    string             `json:"itemTitle"`
	Lat          *float64           `json:"lat,omitempty"`
	Lng          *float64           `json:"lng,omitempty"`
	Name         string             `json:"name"`

	// Source which signal produced this place (caption or vision)
	Source string `json:"source"`
}

// RegisterPushDeviceRequest defines model for RegisterPushDeviceRequest.
type RegisterPushDeviceRequest struct {
	Platform RegisterPushDeviceRequestPlatform `json:"platform"`

	// Token Expo push token, e.g. ExponentPushToken[xxx].
	Token string `json:"token"`
}

// RegisterPushDeviceRequestPlatform defines model for RegisterPushDeviceRequest.Platform.
type RegisterPushDeviceRequestPlatform string

// RelatedItem defines model for RelatedItem.
type RelatedItem struct {
	Distance float64 `json:"distance"`
	Item     Item    `json:"item"`
}

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	Results []SearchResult `json:"results"`

	// Understood How a natural-language query was interpreted (present only when parse=true). Reflects the values actually searched.
	Understood *UnderstoodQuery `json:"understood,omitempty"`
}

// SearchResult defines model for SearchResult.
type SearchResult struct {
	Item  Item    `json:"item"`
	Score float32 `json:"score"`
}

// Settings defines model for Settings.
type Settings struct {
	// KindleEmail Destination e-mail for Send-to-Kindle digests; absent if not configured.
	KindleEmail *openapi_types.Email `json:"kindleEmail,omitempty"`

	// NotifyDailyCap Maximum successful deliveries per day before non-lifecycle notifications defer. Default 10.
	NotifyDailyCap *int `json:"notifyDailyCap,omitempty"`

	// NotifyDigest Channels for Lens digest notifications. Default push.
	NotifyDigest *SettingsNotifyDigest `json:"notifyDigest,omitempty"`

	// NotifyFeedRiver Channels for coalesced feed-river activity. Default off.
	NotifyFeedRiver *SettingsNotifyFeedRiver `json:"notifyFeedRiver,omitempty"`

	// NotifyLifecycle Channels for save-failure notifications. Default push. Exempt from the daily cap.
	NotifyLifecycle *SettingsNotifyLifecycle `json:"notifyLifecycle,omitempty"`

	// NotifyQuietHours Wall-clock range in the user's timezone, e.g. 22:00-07:00. Empty means none.
	NotifyQuietHours *string `json:"notifyQuietHours,omitempty"`

	// NotifyTimezone IANA timezone used for quiet hours and the daily-cap reset, e.g. Europe/London.
	NotifyTimezone *string `json:"notifyTimezone,omitempty"`
}

// SettingsNotifyDigest Channels for Lens digest notifications. Default push.
type SettingsNotifyDigest string

// SettingsNotifyFeedRiver Channels for coalesced feed-river activity. Default off.
type SettingsNotifyFeedRiver string

// SettingsNotifyLifecycle Channels for save-failure notifications. Default push. Exempt from the daily cap.
type SettingsNotifyLifecycle string

// UnderstoodQuery How a natural-language query was interpreted (present only when parse=true). Reflects the values actually searched.
type UnderstoodQuery struct {
	// Color The colour searched, if any.
	Color *string `json:"color,omitempty"`

	// Text The free-text portion searched.
	Text *string `json:"text,omitempty"`

	// Types Card-type filters applied, if any.
	Types *[]UnderstoodQueryTypes `json:"types,omitempty"`
}

// UnderstoodQueryTypes defines model for UnderstoodQuery.Types.
type UnderstoodQueryTypes string

// UnregisterPushDeviceRequest defines model for UnregisterPushDeviceRequest.
type UnregisterPushDeviceRequest struct {
	Token string `json:"token"`
}

// UpdateItemRequest Fields to update on an item. Both userTags and pinned are optional; omit both for a no-op edit that is rejected as a bad request.
type UpdateItemRequest struct {
	// Kept Keep (true) the item in the library independent of its feed. Sets keptAt to now.
	Kept *bool `json:"kept,omitempty"`

	// Pinned Pin (true) or unpin (false) the item on the Desk. Pinning sets pinnedAt to now; unpinning clears it.
	Pinned *bool `json:"pinned,omitempty"`

	// UserTags Full replacement user-tags list. An empty array clears all user tags.
	UserTags *[]string `json:"userTags,omitempty"`
}

// CreateAssetMultipartBody defines parameters for CreateAsset.
type CreateAssetMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// GetFeedItemsParams defines parameters for GetFeedItems.
type GetFeedItemsParams struct {
	Limit  *int                `form:"limit,omitempty" json:"limit,omitempty"`
	FeedId *openapi_types.UUID `form:"feedId,omitempty" json:"feedId,omitempty"`
}

// ImportItemsMultipartBody defines parameters for ImportItems.
type ImportItemsMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// ListItemsParams defines parameters for ListItems.
type ListItemsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateItemLinkJSONBody defines parameters for CreateItemLink.
type CreateItemLinkJSONBody struct {
	ToId openapi_types.UUID `json:"toId"`
}

// SearchItemsParams defines parameters for SearchItems.
type SearchItemsParams struct {
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Color Hex (#RRGGBB) or named colour (e.g. cobalt, terracotta); ranks items by nearest palette colour.
	Color *string `form:"color,omitempty" json:"color,omitempty"`

	// Parse Interpret q as a natural-language query, splitting it into text + colour + card-type filters via the AI provider. Falls back to a plain text search when no AI provider is configured.
	Parse *bool `form:"parse,omitempty" json:"parse,omitempty"`
}

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody = CreateApiKeyRequest

// CreateAssetMultipartRequestBody defines body for CreateAsset for multipart/form-data ContentType.
type CreateAssetMultipartRequestBody CreateAssetMultipartBody

// CreateDeviceLinkJSONRequestBody defines body for CreateDeviceLink for application/json ContentType.
type CreateDeviceLinkJSONRequestBody = CreateDeviceLinkRequest

// ClaimDeviceLinkJSONRequestBody defines body for ClaimDeviceLink for application/json ContentType.
type ClaimDeviceLinkJSONRequestBody = ClaimDeviceLinkRequest

// DriftItemJSONRequestBody defines body for DriftItem for application/json ContentType.
type DriftItemJSONRequestBody = DriftActionRequest

// CreateFeedJSONRequestBody defines body for CreateFeed for application/json ContentType.
type CreateFeedJSONRequestBody = CreateFeedRequest

// ImportItemsMultipartRequestBody defines body for ImportItems for multipart/form-data ContentType.
type ImportItemsMultipartRequestBody ImportItemsMultipartBody

// CreateItemJSONRequestBody defines body for CreateItem for application/json ContentType.
type CreateItemJSONRequestBody = CreateItemRequest

// PatchItemJSONRequestBody defines body for PatchItem for application/json ContentType.
type PatchItemJSONRequestBody = UpdateItemRequest

// CreateItemHighlightJSONRequestBody defines body for CreateItemHighlight for application/json ContentType.
type CreateItemHighlightJSONRequestBody = CreateHighlightRequest

// CreateItemLinkJSONRequestBody defines body for CreateItemLink for application/json ContentType.
type CreateItemLinkJSONRequestBody CreateItemLinkJSONBody

// CreateLensJSONRequestBody defines body for CreateLens for application/json ContentType.
type CreateLensJSONRequestBody = CreateLensRequest

// UpdateLensJSONRequestBody defines body for UpdateLens for application/json ContentType.
type UpdateLensJSONRequestBody = CreateLensRequest

// RegisterPushDeviceJSONRequestBody defines body for RegisterPushDevice for application/json ContentType.
type RegisterPushDeviceJSONRequestBody = RegisterPushDeviceRequest

// UnregisterPushDeviceJSONRequestBody defines body for UnregisterPushDevice for application/json ContentType.
type UnregisterPushDeviceJSONRequestBody = UnregisterPushDeviceRequest

// PatchSettingsJSONRequestBody defines body for PatchSettings for application/json ContentType.
type PatchSettingsJSONRequestBody = PatchSettingsRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /account)
	GetAccount(w http.ResponseWriter, r *http.Request)

	// (GET /api-keys)
	ListApiKeys(w http.ResponseWriter, r *http.Request)

	// (POST /api-keys)
	CreateApiKey(w http.ResponseWriter, r *http.Request)

	// (DELETE /api-keys/{id})
	RevokeApiKey(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (POST /assets)
	CreateAsset(w http.ResponseWriter, r *http.Request)

	// (GET /assets/{id})
	GetAsset(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /desk)
	GetDesk(w http.ResponseWriter, r *http.Request)

	// (POST /device-links)
	CreateDeviceLink(w http.ResponseWriter, r *http.Request)

	// (POST /device-links/claim)
	ClaimDeviceLink(w http.ResponseWriter, r *http.Request)

	// (GET /drift)
	GetDrift(w http.ResponseWriter, r *http.Request)

	// (POST /drift/{id})
	DriftItem(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /export)
	ExportItems(w http.ResponseWriter, r *http.Request)

	// (GET /feed)
	GetFeedItems(w http.ResponseWriter, r *http.Request, params GetFeedItemsParams)

	// (GET /feeds)
	ListFeeds(w http.ResponseWriter, r *http.Request)

	// (POST /feeds)
	CreateFeed(w http.ResponseWriter, r *http.Request)

	// (DELETE /feeds/{id})
	DeleteFeed(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)

	// (DELETE /highlights/{id})
	DeleteHighlight(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (POST /import)
	ImportItems(w http.ResponseWriter, r *http.Request)

	// (GET /items)
	ListItems(w http.ResponseWriter, r *http.Request, params ListItemsParams)

	// (POST /items)
	CreateItem(w http.ResponseWriter, r *http.Request)

	// (DELETE /items/{id})
	DeleteItem(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /items/{id})
	GetItem(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (PATCH /items/{id})
	PatchItem(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /items/{id}/highlights)
	ListItemHighlights(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (POST /items/{id}/highlights)
	CreateItemHighlight(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Send this item to Kindle as an EPUB
	// (POST /items/{id}/kindle)
	SendItemToKindle(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Items linked to this item (both directions)
	// (GET /items/{id}/links)
	ListItemLinks(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Link this item to another (undirected, idempotent)
	// (POST /items/{id}/links)
	CreateItemLink(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Remove a link
	// (DELETE /items/{id}/links/{toId})
	DeleteItemLink(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, toId openapi_types.UUID)
	// Places extracted from this item
	// (GET /items/{id}/places)
	GetItemPlaces(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /items/{id}/related)
	GetRelatedItems(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /lenses)
	ListLenses(w http.ResponseWriter, r *http.Request)

	// (POST /lenses)
	CreateLens(w http.ResponseWriter, r *http.Request)

	// (DELETE /lenses/{id})
	DeleteLens(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /lenses/{id})
	GetLens(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (PATCH /lenses/{id})
	UpdateLens(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /lenses/{id}/items)
	GetLensItems(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Send this Lens's current matches to Kindle as a digest EPUB
	// (POST /lenses/{id}/kindle)
	SendLensToKindle(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// All of the user's extracted places
	// (GET /places)
	ListPlaces(w http.ResponseWriter, r *http.Request)

	// (POST /push-devices)
	RegisterPushDevice(w http.ResponseWriter, r *http.Request)

	// (POST /push-devices/unregister)
	UnregisterPushDevice(w http.ResponseWriter, r *http.Request)

	// (GET /search)
	SearchItems(w http.ResponseWriter, r *http.Request, params SearchItemsParams)

	// (GET /settings)
	GetSettings(w http.ResponseWriter, r *http.Request)

	// (PATCH /settings)
	PatchSettings(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /account)
func (_ Unimplemented) GetAccount(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api-keys)
func (_ Unimplemented) ListApiKeys(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api-keys)
func (_ Unimplemented) CreateApiKey(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /api-keys/{id})
func (_ Unimplemented) RevokeApiKey(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /assets)
func (_ Unimplemented) CreateAsset(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /assets/{id})
func (_ Unimplemented) GetAsset(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /desk)
func (_ Unimplemented) GetDesk(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /device-links)
func (_ Unimplemented) CreateDeviceLink(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /device-links/claim)
func (_ Unimplemented) ClaimDeviceLink(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /drift)
func (_ Unimplemented) GetDrift(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /drift/{id})
func (_ Unimplemented) DriftItem(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /export)
func (_ Unimplemented) ExportItems(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /feed)
func (_ Unimplemented) GetFeedItems(w http.ResponseWriter, r *http.Request, params GetFeedItemsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /feeds)
func (_ Unimplemented) ListFeeds(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /feeds)
func (_ Unimplemented) CreateFeed(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /feeds/{id})
func (_ Unimplemented) DeleteFeed(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /healthz)
func (_ Unimplemented) GetHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /highlights/{id})
func (_ Unimplemented) DeleteHighlight(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /import)
func (_ Unimplemented) ImportItems(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /items)
func (_ Unimplemented) ListItems(w http.ResponseWriter, r *http.Request, params ListItemsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /items)
func (_ Unimplemented) CreateItem(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /items/{id})
func (_ Unimplemented) DeleteItem(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /items/{id})
func (_ Unimplemented) GetItem(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /items/{id})
func (_ Unimplemented) PatchItem(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /items/{id}/highlights)
func (_ Unimplemented) ListItemHighlights(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /items/{id}/highlights)
func (_ Unimplemented) CreateItemHighlight(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Send this item to Kindle as an EPUB
// (POST /items/{id}/kindle)
func (_ Unimplemented) SendItemToKindle(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Items linked to this item (both directions)
// (GET /items/{id}/links)
func (_ Unimplemented) ListItemLinks(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Link this item to another (undirected, idempotent)
// (POST /items/{id}/links)
func (_ Unimplemented) CreateItemLink(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove a link
// (DELETE /items/{id}/links/{toId})
func (_ Unimplemented) DeleteItemLink(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, toId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Places extracted from this item
// (GET /items/{id}/places)
func (_ Unimplemented) GetItemPlaces(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /items/{id}/related)
func (_ Unimplemented) GetRelatedItems(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /lenses)
func (_ Unimplemented) ListLenses(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /lenses)
func (_ Unimplemented) CreateLens(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /lenses/{id})
func (_ Unimplemented) DeleteLens(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /lenses/{id})
func (_ Unimplemented) GetLens(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /lenses/{id})
func (_ Unimplemented) UpdateLens(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /lenses/{id}/items)
func (_ Unimplemented) GetLensItems(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Send this Lens's current matches to Kindle as a digest EPUB
// (POST /lenses/{id}/kindle)
func (_ Unimplemented) SendLensToKindle(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// All of the user's extracted places
// (GET /places)
func (_ Unimplemented) ListPlaces(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /push-devices)
func (_ Unimplemented) RegisterPushDevice(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /push-devices/unregister)
func (_ Unimplemented) UnregisterPushDevice(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /search)
func (_ Unimplemented) SearchItems(w http.ResponseWriter, r *http.Request, params SearchItemsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /settings)
func (_ Unimplemented) GetSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /settings)
func (_ Unimplemented) PatchSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAccount operation middleware
func (siw *ServerInterfaceWrapper) GetAccount(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccount(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListApiKeys operation middleware
func (siw *ServerInterfaceWrapper) ListApiKeys(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListApiKeys(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateApiKey operation middleware
func (siw *ServerInterfaceWrapper) CreateApiKey(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateApiKey(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeApiKey operation middleware
func (siw *ServerInterfaceWrapper) RevokeApiKey(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeApiKey(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAsset operation middleware
func (siw *ServerInterfaceWrapper) CreateAsset(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAsset(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAsset operation middleware
func (siw *ServerInterfaceWrapper) GetAsset(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAsset(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDesk operation middleware
func (siw *ServerInterfaceWrapper) GetDesk(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDesk(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDeviceLink operation middleware
func (siw *ServerInterfaceWrapper) CreateDeviceLink(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDeviceLink(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ClaimDeviceLink operation middleware
func (siw *ServerInterfaceWrapper) ClaimDeviceLink(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ClaimDeviceLink(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDrift operation middleware
func (siw *ServerInterfaceWrapper) GetDrift(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDrift(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DriftItem operation middleware
func (siw *ServerInterfaceWrapper) DriftItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DriftItem(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportItems operation middleware
func (siw *ServerInterfaceWrapper) ExportItems(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportItems(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFeedItems operation middleware
func (siw *ServerInterfaceWrapper) GetFeedItems(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetFeedItemsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "feedId" -------------

	err = runtime.BindQueryParameter("form", true, false, "feedId", r.URL.Query(), &params.FeedId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "feedId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFeedItems(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListFeeds operation middleware
func (siw *ServerInterfaceWrapper) ListFeeds(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFeeds(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateFeed operation middleware
func (siw *ServerInterfaceWrapper) CreateFeed(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateFeed(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteFeed operation middleware
func (siw *ServerInterfaceWrapper) DeleteFeed(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteFeed(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteHighlight operation middleware
func (siw *ServerInterfaceWrapper) DeleteHighlight(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteHighlight(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ImportItems operation middleware
func (siw *ServerInterfaceWrapper) ImportItems(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ImportItems(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListItems operation middleware
func (siw *ServerInterfaceWrapper) ListItems(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListItemsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListItems(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateItem operation middleware
func (siw *ServerInterfaceWrapper) CreateItem(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateItem(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteItem(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetItem operation middleware
func (siw *ServerInterfaceWrapper) GetItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetItem(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchItem operation middleware
func (siw *ServerInterfaceWrapper) PatchItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchItem(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListItemHighlights operation middleware
func (siw *ServerInterfaceWrapper) ListItemHighlights(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListItemHighlights(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateItemHighlight operation middleware
func (siw *ServerInterfaceWrapper) CreateItemHighlight(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateItemHighlight(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendItemToKindle operation middleware
func (siw *ServerInterfaceWrapper) SendItemToKindle(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendItemToKindle(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListItemLinks operation middleware
func (siw *ServerInterfaceWrapper) ListItemLinks(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListItemLinks(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateItemLink operation middleware
func (siw *ServerInterfaceWrapper) CreateItemLink(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateItemLink(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteItemLink operation middleware
func (siw *ServerInterfaceWrapper) DeleteItemLink(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "toId" -------------
	var toId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "toId", chi.URLParam(r, "toId"), &toId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "toId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteItemLink(w, r, id, toId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetItemPlaces operation middleware
func (siw *ServerInterfaceWrapper) GetItemPlaces(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetItemPlaces(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRelatedItems operation middleware
func (siw *ServerInterfaceWrapper) GetRelatedItems(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRelatedItems(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListLenses operation middleware
func (siw *ServerInterfaceWrapper) ListLenses(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLenses(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateLens operation middleware
func (siw *ServerInterfaceWrapper) CreateLens(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateLens(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteLens operation middleware
func (siw *ServerInterfaceWrapper) DeleteLens(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteLens(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLens operation middleware
func (siw *ServerInterfaceWrapper) GetLens(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLens(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateLens operation middleware
func (siw *ServerInterfaceWrapper) UpdateLens(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateLens(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLensItems operation middleware
func (siw *ServerInterfaceWrapper) GetLensItems(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLensItems(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendLensToKindle operation middleware
func (siw *ServerInterfaceWrapper) SendLensToKindle(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendLensToKindle(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPlaces operation middleware
func (siw *ServerInterfaceWrapper) ListPlaces(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPlaces(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterPushDevice operation middleware
func (siw *ServerInterfaceWrapper) RegisterPushDevice(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterPushDevice(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UnregisterPushDevice operation middleware
func (siw *ServerInterfaceWrapper) UnregisterPushDevice(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UnregisterPushDevice(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchItems operation middleware
func (siw *ServerInterfaceWrapper) SearchItems(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchItemsParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", r.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	// ------------- Optional query parameter "color" -------------

	err = runtime.BindQueryParameter("form", true, false, "color", r.URL.Query(), &params.Color)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "color", Err: err})
		return
	}

	// ------------- Optional query parameter "parse" -------------

	err = runtime.BindQueryParameter("form", true, false, "parse", r.URL.Query(), &params.Parse)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "parse", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchItems(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSettings operation middleware
func (siw *ServerInterfaceWrapper) GetSettings(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchSettings operation middleware
func (siw *ServerInterfaceWrapper) PatchSettings(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/account", wrapper.GetAccount)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api-keys", wrapper.ListApiKeys)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api-keys", wrapper.CreateApiKey)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api-keys/{id}", wrapper.RevokeApiKey)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/assets", wrapper.CreateAsset)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/assets/{id}", wrapper.GetAsset)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/desk", wrapper.GetDesk)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/device-links", wrapper.CreateDeviceLink)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/device-links/claim", wrapper.ClaimDeviceLink)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/drift", wrapper.GetDrift)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/drift/{id}", wrapper.DriftItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/export", wrapper.ExportItems)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/feed", wrapper.GetFeedItems)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/feeds", wrapper.ListFeeds)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/feeds", wrapper.CreateFeed)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/feeds/{id}", wrapper.DeleteFeed)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealthz)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/highlights/{id}", wrapper.DeleteHighlight)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/import", wrapper.ImportItems)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/items", wrapper.ListItems)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/items", wrapper.CreateItem)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/items/{id}", wrapper.DeleteItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/items/{id}", wrapper.GetItem)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/items/{id}", wrapper.PatchItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/items/{id}/highlights", wrapper.ListItemHighlights)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/items/{id}/highlights", wrapper.CreateItemHighlight)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/items/{id}/kindle", wrapper.SendItemToKindle)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/items/{id}/links", wrapper.ListItemLinks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/items/{id}/links", wrapper.CreateItemLink)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/items/{id}/links/{toId}", wrapper.DeleteItemLink)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/items/{id}/places", wrapper.GetItemPlaces)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/items/{id}/related", wrapper.GetRelatedItems)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/lenses", wrapper.ListLenses)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/lenses", wrapper.CreateLens)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/lenses/{id}", wrapper.DeleteLens)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/lenses/{id}", wrapper.GetLens)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/lenses/{id}", wrapper.UpdateLens)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/lenses/{id}/items", wrapper.GetLensItems)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/lenses/{id}/kindle", wrapper.SendLensToKindle)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/places", wrapper.ListPlaces)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/push-devices", wrapper.RegisterPushDevice)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/push-devices/unregister", wrapper.UnregisterPushDevice)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/search", wrapper.SearchItems)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/settings", wrapper.GetSettings)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/settings", wrapper.PatchSettings)
	})

	return r
}
