// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ItemCardType.
const (
	ItemCardTypeArticle ItemCardType = "article"
	ItemCardTypeBook    ItemCardType = "book"
	ItemCardTypeImage   ItemCardType = "image"
	ItemCardTypeNote    ItemCardType = "note"
	ItemCardTypeProduct ItemCardType = "product"
	ItemCardTypeQuote   ItemCardType = "quote"
	ItemCardTypeRecipe  ItemCardType = "recipe"
	ItemCardTypeTweet   ItemCardType = "tweet"
	ItemCardTypeVideo   ItemCardType = "video"
)

// Defines values for ItemStatus.
const (
	ItemStatusEnriched ItemStatus = "enriched"
	ItemStatusFailed   ItemStatus = "failed"
	ItemStatusPending  ItemStatus = "pending"
)

// Defines values for ItemDetailCardType.
const (
	ItemDetailCardTypeArticle ItemDetailCardType = "article"
	ItemDetailCardTypeBook    ItemDetailCardType = "book"
	ItemDetailCardTypeImage   ItemDetailCardType = "image"
	ItemDetailCardTypeNote    ItemDetailCardType = "note"
	ItemDetailCardTypeProduct ItemDetailCardType = "product"
	ItemDetailCardTypeQuote   ItemDetailCardType = "quote"
	ItemDetailCardTypeRecipe  ItemDetailCardType = "recipe"
	ItemDetailCardTypeTweet   ItemDetailCardType = "tweet"
	ItemDetailCardTypeVideo   ItemDetailCardType = "video"
)

// Defines values for ItemDetailStatus.
const (
	ItemDetailStatusEnriched ItemDetailStatus = "enriched"
	ItemDetailStatusFailed   ItemDetailStatus = "failed"
	ItemDetailStatusPending  ItemDetailStatus = "pending"
)

// Defines values for LensRuleTypes.
const (
	LensRuleTypesArticle LensRuleTypes = "article"
	LensRuleTypesBook    LensRuleTypes = "book"
	LensRuleTypesImage   LensRuleTypes = "image"
	LensRuleTypesNote    LensRuleTypes = "note"
	LensRuleTypesProduct LensRuleTypes = "product"
	LensRuleTypesQuote   LensRuleTypes = "quote"
	LensRuleTypesRecipe  LensRuleTypes = "recipe"
	LensRuleTypesTweet   LensRuleTypes = "tweet"
	LensRuleTypesVideo   LensRuleTypes = "video"
)

// Defines values for UnderstoodQueryTypes.
const (
	UnderstoodQueryTypesArticle UnderstoodQueryTypes = "article"
	UnderstoodQueryTypesBook    UnderstoodQueryTypes = "book"
	UnderstoodQueryTypesImage   UnderstoodQueryTypes = "image"
	UnderstoodQueryTypesNote    UnderstoodQueryTypes = "note"
	UnderstoodQueryTypesProduct UnderstoodQueryTypes = "product"
	UnderstoodQueryTypesQuote   UnderstoodQueryTypes = "quote"
	UnderstoodQueryTypesRecipe  UnderstoodQueryTypes = "recipe"
	UnderstoodQueryTypesTweet   UnderstoodQueryTypes = "tweet"
	UnderstoodQueryTypesVideo   UnderstoodQueryTypes = "video"
)

// CreateFeedRequest defines model for CreateFeedRequest.
type CreateFeedRequest struct {
	Url string `json:"url"`
}

// CreateItemRequest Exactly one of url or note must be provided.
type CreateItemRequest struct {
	Note *string `json:"note,omitempty"`
	Url  *string `json:"url,omitempty"`
}

// CreateLensRequest defines model for CreateLensRequest.
type CreateLensRequest struct {
	Name string `json:"name"`

	// Rule A saved search rule. At least one of q, color, or types must be set. Applied like /search: q is text (FTS + vector), color ranks by palette proximity, types narrows by card type.
	Rule LensRule `json:"rule"`
}

// DriftActionRequest defines model for DriftActionRequest.
type DriftActionRequest struct {
	// Keep Keep the item (pins it to the Desk); false lets it go.
	Keep bool `json:"keep"`
}

// DriftResponse defines model for DriftResponse.
type DriftResponse struct {
	Items []Item `json:"items"`

	// Total Total current drift candidates (for the 'n of total' line).
	Total int `json:"total"`
}

// Feed defines model for Feed.
type Feed struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`

	// LastPolledAt Absent until the feed has been polled at least once.
	LastPolledAt *time.Time `json:"lastPolledAt,omitempty"`

	// LastStatus 'ok' or 'error: …' from the most recent poll; empty before the first poll.
	LastStatus string `json:"lastStatus"`
	SiteUrl    string `json:"siteUrl"`
	Title      string `json:"title"`
	Url        string `json:"url"`
}

// ImportResult Summary of a bulk import.
type ImportResult struct {
	// Failed Links rejected (not a valid http(s) URL) or that failed to save.
	Failed int `json:"failed"`

	// Imported New items created (and queued for enrichment).
	Imported int `json:"imported"`

	// Skipped Links skipped as already saved or duplicated within the file.
	Skipped int `json:"skipped"`

	// Total Links found in the file.
	Total int `json:"total"`
}

// Item defines model for Item.
type Item struct {
	CardType     *ItemCardType      `json:"cardType,omitempty"`
	CreatedAt    time.Time          `json:"createdAt"`
	Id           openapi_types.UUID `json:"id"`
	LeadImageUrl *string            `json:"leadImageUrl,omitempty"`
	Palette      *[]string          `json:"palette,omitempty"`

	// PinnedAt When the item was pinned to the Desk; null if not pinned.
	PinnedAt *time.Time `json:"pinnedAt"`
	Status   ItemStatus `json:"status"`
	Summary  *string    `json:"summary,omitempty"`
	Tags     *[]string  `json:"tags,omitempty"`
	Title    *string    `json:"title,omitempty"`
	Url      string     `json:"url"`
	UserTags *[]string  `json:"userTags,omitempty"`
}

// ItemCardType defines model for Item.CardType.
type ItemCardType string

// ItemStatus defines model for Item.Status.
type ItemStatus string

// ItemDetail defines model for ItemDetail.
type ItemDetail struct {
	Body         string              `json:"body"`
	CardType     *ItemDetailCardType `json:"cardType,omitempty"`
	CreatedAt    time.Time           `json:"createdAt"`
	Id           openapi_types.UUID  `json:"id"`
	LeadImageUrl *string             `json:"leadImageUrl,omitempty"`
	Palette      *[]string           `json:"palette,omitempty"`

	// PinnedAt When the item was pinned to the Desk; null if not pinned.
	PinnedAt *time.Time       `json:"pinnedAt"`
	Status   ItemDetailStatus `json:"status"`
	Summary  *string          `json:"summary,omitempty"`
	Tags     *[]string        `json:"tags,omitempty"`
	Title    *string          `json:"title,omitempty"`
	Url      string           `json:"url"`
	UserTags *[]string        `json:"userTags,omitempty"`
}

// ItemDetailCardType defines model for ItemDetail.CardType.
type ItemDetailCardType string

// ItemDetailStatus defines model for ItemDetail.Status.
type ItemDetailStatus string

// Lens defines model for Lens.
type Lens struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`

	// Rule A saved search rule. At least one of q, color, or types must be set. Applied like /search: q is text (FTS + vector), color ranks by palette proximity, types narrows by card type.
	Rule LensRule `json:"rule"`
}

// LensRule A saved search rule. At least one of q, color, or types must be set. Applied like /search: q is text (FTS + vector), color ranks by palette proximity, types narrows by card type.
type LensRule struct {
	// Color Hex (#RRGGBB) or named colour (e.g. cobalt).
	Color *string `json:"color,omitempty"`

	// Q Free-text query.
	Q *string `json:"q,omitempty"`

	// Types Card types to include.
	Types *[]LensRuleTypes `json:"types,omitempty"`
}

// LensRuleTypes defines model for LensRule.Types.
type LensRuleTypes string

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	Results []SearchResult `json:"results"`

	// Understood How a natural-language query was interpreted (present only when parse=true). Reflects the values actually searched.
	Understood *UnderstoodQuery `json:"understood,omitempty"`
}

// SearchResult defines model for SearchResult.
type SearchResult struct {
	Item  Item    `json:"item"`
	Score float32 `json:"score"`
}

// UnderstoodQuery How a natural-language query was interpreted (present only when parse=true). Reflects the values actually searched.
type UnderstoodQuery struct {
	// Color The colour searched, if any.
	Color *string `json:"color,omitempty"`

	// Text The free-text portion searched.
	Text *string `json:"text,omitempty"`

	// Types Card-type filters applied, if any.
	Types *[]UnderstoodQueryTypes `json:"types,omitempty"`
}

// UnderstoodQueryTypes defines model for UnderstoodQuery.Types.
type UnderstoodQueryTypes string

// UpdateItemRequest Fields to update on an item. Both userTags and pinned are optional; omit both for a no-op edit that is rejected as a bad request.
type UpdateItemRequest struct {
	// Pinned Pin (true) or unpin (false) the item on the Desk. Pinning sets pinnedAt to now; unpinning clears it.
	Pinned *bool `json:"pinned,omitempty"`

	// UserTags Full replacement user-tags list. An empty array clears all user tags.
	UserTags *[]string `json:"userTags,omitempty"`
}

// CreateAssetMultipartBody defines parameters for CreateAsset.
type CreateAssetMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// ImportItemsMultipartBody defines parameters for ImportItems.
type ImportItemsMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// ListItemsParams defines parameters for ListItems.
type ListItemsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateItemLinkJSONBody defines parameters for CreateItemLink.
type CreateItemLinkJSONBody struct {
	ToId openapi_types.UUID `json:"toId"`
}

// SearchItemsParams defines parameters for SearchItems.
type SearchItemsParams struct {
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Color Hex (#RRGGBB) or named colour (e.g. cobalt, terracotta); ranks items by nearest palette colour.
	Color *string `form:"color,omitempty" json:"color,omitempty"`

	// Parse Interpret q as a natural-language query, splitting it into text + colour + card-type filters via the AI provider. Falls back to a plain text search when no AI provider is configured.
	Parse *bool `form:"parse,omitempty" json:"parse,omitempty"`
}

// CreateAssetMultipartRequestBody defines body for CreateAsset for multipart/form-data ContentType.
type CreateAssetMultipartRequestBody CreateAssetMultipartBody

// DriftItemJSONRequestBody defines body for DriftItem for application/json ContentType.
type DriftItemJSONRequestBody = DriftActionRequest

// CreateFeedJSONRequestBody defines body for CreateFeed for application/json ContentType.
type CreateFeedJSONRequestBody = CreateFeedRequest

// ImportItemsMultipartRequestBody defines body for ImportItems for multipart/form-data ContentType.
type ImportItemsMultipartRequestBody ImportItemsMultipartBody

// CreateItemJSONRequestBody defines body for CreateItem for application/json ContentType.
type CreateItemJSONRequestBody = CreateItemRequest

// PatchItemJSONRequestBody defines body for PatchItem for application/json ContentType.
type PatchItemJSONRequestBody = UpdateItemRequest

// CreateItemLinkJSONRequestBody defines body for CreateItemLink for application/json ContentType.
type CreateItemLinkJSONRequestBody CreateItemLinkJSONBody

// CreateLensJSONRequestBody defines body for CreateLens for application/json ContentType.
type CreateLensJSONRequestBody = CreateLensRequest

// UpdateLensJSONRequestBody defines body for UpdateLens for application/json ContentType.
type UpdateLensJSONRequestBody = CreateLensRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /assets)
	CreateAsset(w http.ResponseWriter, r *http.Request)

	// (GET /assets/{id})
	GetAsset(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /desk)
	GetDesk(w http.ResponseWriter, r *http.Request)

	// (GET /drift)
	GetDrift(w http.ResponseWriter, r *http.Request)

	// (POST /drift/{id})
	DriftItem(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /export)
	ExportItems(w http.ResponseWriter, r *http.Request)

	// (GET /feeds)
	ListFeeds(w http.ResponseWriter, r *http.Request)

	// (POST /feeds)
	CreateFeed(w http.ResponseWriter, r *http.Request)

	// (DELETE /feeds/{id})
	DeleteFeed(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)

	// (POST /import)
	ImportItems(w http.ResponseWriter, r *http.Request)

	// (GET /items)
	ListItems(w http.ResponseWriter, r *http.Request, params ListItemsParams)

	// (POST /items)
	CreateItem(w http.ResponseWriter, r *http.Request)

	// (DELETE /items/{id})
	DeleteItem(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /items/{id})
	GetItem(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (PATCH /items/{id})
	PatchItem(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Items linked to this item (both directions)
	// (GET /items/{id}/links)
	ListItemLinks(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Link this item to another (undirected, idempotent)
	// (POST /items/{id}/links)
	CreateItemLink(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Remove a link
	// (DELETE /items/{id}/links/{toId})
	DeleteItemLink(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, toId openapi_types.UUID)

	// (GET /lenses)
	ListLenses(w http.ResponseWriter, r *http.Request)

	// (POST /lenses)
	CreateLens(w http.ResponseWriter, r *http.Request)

	// (DELETE /lenses/{id})
	DeleteLens(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /lenses/{id})
	GetLens(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (PATCH /lenses/{id})
	UpdateLens(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /lenses/{id}/items)
	GetLensItems(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /search)
	SearchItems(w http.ResponseWriter, r *http.Request, params SearchItemsParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (POST /assets)
func (_ Unimplemented) CreateAsset(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /assets/{id})
func (_ Unimplemented) GetAsset(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /desk)
func (_ Unimplemented) GetDesk(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /drift)
func (_ Unimplemented) GetDrift(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /drift/{id})
func (_ Unimplemented) DriftItem(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /export)
func (_ Unimplemented) ExportItems(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /feeds)
func (_ Unimplemented) ListFeeds(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /feeds)
func (_ Unimplemented) CreateFeed(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /feeds/{id})
func (_ Unimplemented) DeleteFeed(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /healthz)
func (_ Unimplemented) GetHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /import)
func (_ Unimplemented) ImportItems(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /items)
func (_ Unimplemented) ListItems(w http.ResponseWriter, r *http.Request, params ListItemsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /items)
func (_ Unimplemented) CreateItem(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /items/{id})
func (_ Unimplemented) DeleteItem(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /items/{id})
func (_ Unimplemented) GetItem(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /items/{id})
func (_ Unimplemented) PatchItem(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Items linked to this item (both directions)
// (GET /items/{id}/links)
func (_ Unimplemented) ListItemLinks(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Link this item to another (undirected, idempotent)
// (POST /items/{id}/links)
func (_ Unimplemented) CreateItemLink(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove a link
// (DELETE /items/{id}/links/{toId})
func (_ Unimplemented) DeleteItemLink(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, toId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /lenses)
func (_ Unimplemented) ListLenses(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /lenses)
func (_ Unimplemented) CreateLens(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /lenses/{id})
func (_ Unimplemented) DeleteLens(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /lenses/{id})
func (_ Unimplemented) GetLens(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /lenses/{id})
func (_ Unimplemented) UpdateLens(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /lenses/{id}/items)
func (_ Unimplemented) GetLensItems(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /search)
func (_ Unimplemented) SearchItems(w http.ResponseWriter, r *http.Request, params SearchItemsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateAsset operation middleware
func (siw *ServerInterfaceWrapper) CreateAsset(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAsset(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAsset operation middleware
func (siw *ServerInterfaceWrapper) GetAsset(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAsset(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDesk operation middleware
func (siw *ServerInterfaceWrapper) GetDesk(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDesk(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDrift operation middleware
func (siw *ServerInterfaceWrapper) GetDrift(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDrift(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DriftItem operation middleware
func (siw *ServerInterfaceWrapper) DriftItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DriftItem(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportItems operation middleware
func (siw *ServerInterfaceWrapper) ExportItems(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportItems(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListFeeds operation middleware
func (siw *ServerInterfaceWrapper) ListFeeds(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFeeds(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateFeed operation middleware
func (siw *ServerInterfaceWrapper) CreateFeed(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateFeed(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteFeed operation middleware
func (siw *ServerInterfaceWrapper) DeleteFeed(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteFeed(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ImportItems operation middleware
func (siw *ServerInterfaceWrapper) ImportItems(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ImportItems(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListItems operation middleware
func (siw *ServerInterfaceWrapper) ListItems(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListItemsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListItems(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateItem operation middleware
func (siw *ServerInterfaceWrapper) CreateItem(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateItem(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteItem(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetItem operation middleware
func (siw *ServerInterfaceWrapper) GetItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetItem(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchItem operation middleware
func (siw *ServerInterfaceWrapper) PatchItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchItem(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListItemLinks operation middleware
func (siw *ServerInterfaceWrapper) ListItemLinks(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListItemLinks(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateItemLink operation middleware
func (siw *ServerInterfaceWrapper) CreateItemLink(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateItemLink(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteItemLink operation middleware
func (siw *ServerInterfaceWrapper) DeleteItemLink(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "toId" -------------
	var toId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "toId", chi.URLParam(r, "toId"), &toId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "toId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteItemLink(w, r, id, toId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListLenses operation middleware
func (siw *ServerInterfaceWrapper) ListLenses(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLenses(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateLens operation middleware
func (siw *ServerInterfaceWrapper) CreateLens(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateLens(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteLens operation middleware
func (siw *ServerInterfaceWrapper) DeleteLens(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteLens(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLens operation middleware
func (siw *ServerInterfaceWrapper) GetLens(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLens(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateLens operation middleware
func (siw *ServerInterfaceWrapper) UpdateLens(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateLens(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLensItems operation middleware
func (siw *ServerInterfaceWrapper) GetLensItems(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLensItems(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchItems operation middleware
func (siw *ServerInterfaceWrapper) SearchItems(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchItemsParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", r.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	// ------------- Optional query parameter "color" -------------

	err = runtime.BindQueryParameter("form", true, false, "color", r.URL.Query(), &params.Color)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "color", Err: err})
		return
	}

	// ------------- Optional query parameter "parse" -------------

	err = runtime.BindQueryParameter("form", true, false, "parse", r.URL.Query(), &params.Parse)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "parse", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchItems(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/assets", wrapper.CreateAsset)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/assets/{id}", wrapper.GetAsset)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/desk", wrapper.GetDesk)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/drift", wrapper.GetDrift)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/drift/{id}", wrapper.DriftItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/export", wrapper.ExportItems)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/feeds", wrapper.ListFeeds)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/feeds", wrapper.CreateFeed)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/feeds/{id}", wrapper.DeleteFeed)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealthz)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/import", wrapper.ImportItems)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/items", wrapper.ListItems)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/items", wrapper.CreateItem)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/items/{id}", wrapper.DeleteItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/items/{id}", wrapper.GetItem)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/items/{id}", wrapper.PatchItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/items/{id}/links", wrapper.ListItemLinks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/items/{id}/links", wrapper.CreateItemLink)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/items/{id}/links/{toId}", wrapper.DeleteItemLink)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/lenses", wrapper.ListLenses)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/lenses", wrapper.CreateLens)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/lenses/{id}", wrapper.DeleteLens)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/lenses/{id}", wrapper.GetLens)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/lenses/{id}", wrapper.UpdateLens)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/lenses/{id}/items", wrapper.GetLensItems)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/search", wrapper.SearchItems)
	})

	return r
}
