// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: assets.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (user_id, item_id, content_type, byte_size, original_filename)
VALUES ($1, $2, $3, $4, $5) RETURNING id, user_id, item_id, content_type, byte_size, original_filename, created_at
`

type CreateAssetParams struct {
	UserID           uuid.UUID
	ItemID           pgtype.UUID
	ContentType      string
	ByteSize         int64
	OriginalFilename string
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.UserID,
		arg.ItemID,
		arg.ContentType,
		arg.ByteSize,
		arg.OriginalFilename,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.ContentType,
		&i.ByteSize,
		&i.OriginalFilename,
		&i.CreatedAt,
	)
	return i, err
}

const getAsset = `-- name: GetAsset :one
SELECT id, user_id, item_id, content_type, byte_size, original_filename, created_at FROM assets WHERE user_id = $1 AND id = $2
`

type GetAssetParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) GetAsset(ctx context.Context, arg GetAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, arg.UserID, arg.ID)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.ContentType,
		&i.ByteSize,
		&i.OriginalFilename,
		&i.CreatedAt,
	)
	return i, err
}

const setAssetByteSize = `-- name: SetAssetByteSize :exec
UPDATE assets SET byte_size = $3 WHERE user_id = $1 AND id = $2
`

type SetAssetByteSizeParams struct {
	UserID   uuid.UUID
	ID       uuid.UUID
	ByteSize int64
}

func (q *Queries) SetAssetByteSize(ctx context.Context, arg SetAssetByteSizeParams) error {
	_, err := q.db.Exec(ctx, setAssetByteSize, arg.UserID, arg.ID, arg.ByteSize)
	return err
}
