// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDeviceLink = `-- name: ClaimDeviceLink :one
UPDATE device_links SET claimed_at = now()
WHERE code_hash = $1 AND claimed_at IS NULL AND expires_at > now()
RETURNING user_id
`

// Atomic single-use claim: the row transitions from unclaimed to claimed in
// one statement, so concurrent claims of the same code can only succeed once.
func (q *Queries) ClaimDeviceLink(ctx context.Context, codeHash []byte) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, claimDeviceLink, codeHash)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, name, key_hash, prefix) VALUES ($1, $2, $3, $4) RETURNING id, user_id, name, key_hash, prefix, created_at, last_used_at, revoked_at
`

type CreateAPIKeyParams struct {
	UserID  uuid.UUID
	Name    string
	KeyHash []byte
	Prefix  string
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.UserID,
		arg.Name,
		arg.KeyHash,
		arg.Prefix,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.Prefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createDeviceLink = `-- name: CreateDeviceLink :one
INSERT INTO device_links (code_hash, user_id, device_hint, expires_at) VALUES ($1, $2, $3, $4) RETURNING code_hash, user_id, device_hint, created_at, expires_at, claimed_at
`

type CreateDeviceLinkParams struct {
	CodeHash   []byte
	UserID     uuid.UUID
	DeviceHint string
	ExpiresAt  pgtype.Timestamptz
}

func (q *Queries) CreateDeviceLink(ctx context.Context, arg CreateDeviceLinkParams) (DeviceLink, error) {
	row := q.db.QueryRow(ctx, createDeviceLink,
		arg.CodeHash,
		arg.UserID,
		arg.DeviceHint,
		arg.ExpiresAt,
	)
	var i DeviceLink
	err := row.Scan(
		&i.CodeHash,
		&i.UserID,
		&i.DeviceHint,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ClaimedAt,
	)
	return i, err
}

const createUserFromClerk = `-- name: CreateUserFromClerk :one
INSERT INTO users (clerk_user_id, email) VALUES ($1, $2) RETURNING id, created_at, clerk_user_id, email
`

type CreateUserFromClerkParams struct {
	ClerkUserID pgtype.Text
	Email       string
}

func (q *Queries) CreateUserFromClerk(ctx context.Context, arg CreateUserFromClerkParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserFromClerk, arg.ClerkUserID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ClerkUserID,
		&i.Email,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT
    api_keys.id AS api_key_id,
    api_keys.user_id,
    api_keys.name,
    api_keys.prefix,
    api_keys.last_used_at,
    users.email,
    users.clerk_user_id
FROM api_keys
JOIN users ON users.id = api_keys.user_id
WHERE api_keys.key_hash = $1 AND api_keys.revoked_at IS NULL
`

type GetAPIKeyByHashRow struct {
	ApiKeyID    uuid.UUID
	UserID      uuid.UUID
	Name        string
	Prefix      string
	LastUsedAt  pgtype.Timestamptz
	Email       string
	ClerkUserID pgtype.Text
}

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash []byte) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ApiKeyID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.LastUsedAt,
		&i.Email,
		&i.ClerkUserID,
	)
	return i, err
}

const getUserByClerkID = `-- name: GetUserByClerkID :one
SELECT id, created_at, clerk_user_id, email FROM users WHERE clerk_user_id = $1
`

func (q *Queries) GetUserByClerkID(ctx context.Context, clerkUserID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByClerkID, clerkUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ClerkUserID,
		&i.Email,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, user_id, name, key_hash, prefix, created_at, last_used_at, revoked_at FROM api_keys WHERE user_id = $1 ORDER BY created_at DESC
`

// Includes revoked keys (revoked_at set) so callers can render key history.
func (q *Queries) ListAPIKeys(ctx context.Context, userID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeyHash,
			&i.Prefix,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys SET revoked_at = now() WHERE user_id = $1 AND id = $2 AND revoked_at IS NULL
`

type RevokeAPIKeyParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, id)
	return err
}
