// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: feeds.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (user_id, url, title, site_url) VALUES ($1, $2, $3, $4) RETURNING id, user_id, url, title, site_url, last_polled_at, last_status, created_at
`

type CreateFeedParams struct {
	UserID  uuid.UUID
	Url     string
	Title   string
	SiteUrl string
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRow(ctx, createFeed,
		arg.UserID,
		arg.Url,
		arg.Title,
		arg.SiteUrl,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Title,
		&i.SiteUrl,
		&i.LastPolledAt,
		&i.LastStatus,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFeed = `-- name: DeleteFeed :execrows
DELETE FROM feeds WHERE user_id = $1 AND id = $2
`

type DeleteFeedParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteFeed(ctx context.Context, arg DeleteFeedParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFeed, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFeed = `-- name: GetFeed :one
SELECT id, user_id, url, title, site_url, last_polled_at, last_status, created_at FROM feeds WHERE user_id = $1 AND id = $2
`

type GetFeedParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) GetFeed(ctx context.Context, arg GetFeedParams) (Feed, error) {
	row := q.db.QueryRow(ctx, getFeed, arg.UserID, arg.ID)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Title,
		&i.SiteUrl,
		&i.LastPolledAt,
		&i.LastStatus,
		&i.CreatedAt,
	)
	return i, err
}

const listFeeds = `-- name: ListFeeds :many
SELECT id, user_id, url, title, site_url, last_polled_at, last_status, created_at FROM feeds WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListFeeds(ctx context.Context, userID uuid.UUID) ([]Feed, error) {
	rows, err := q.db.Query(ctx, listFeeds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
			&i.SiteUrl,
			&i.LastPolledAt,
			&i.LastStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedsDue = `-- name: ListFeedsDue :many
SELECT id, user_id, url, title, site_url, last_polled_at, last_status, created_at FROM feeds WHERE last_polled_at IS NULL OR last_polled_at < $1 ORDER BY last_polled_at ASC NULLS FIRST
`

// Cross-user by design: the periodic poller runs system-wide, refreshing every
// feed whose last poll is null or older than the cutoff. Items it saves are
// still scoped to each feed's own user_id.
func (q *Queries) ListFeedsDue(ctx context.Context, lastPolledAt pgtype.Timestamptz) ([]Feed, error) {
	rows, err := q.db.Query(ctx, listFeedsDue, lastPolledAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
			&i.SiteUrl,
			&i.LastPolledAt,
			&i.LastStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFeedPolled = `-- name: SetFeedPolled :exec
UPDATE feeds SET last_polled_at = $3, last_status = $4 WHERE user_id = $1 AND id = $2
`

type SetFeedPolledParams struct {
	UserID       uuid.UUID
	ID           uuid.UUID
	LastPolledAt pgtype.Timestamptz
	LastStatus   string
}

func (q *Queries) SetFeedPolled(ctx context.Context, arg SetFeedPolledParams) error {
	_, err := q.db.Exec(ctx, setFeedPolled,
		arg.UserID,
		arg.ID,
		arg.LastPolledAt,
		arg.LastStatus,
	)
	return err
}
