// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: items.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (user_id, url, body) VALUES ($1, $2, $3) RETURNING id, user_id, url, title, body, lead_image_url, summary, tags, card_type, status, created_at, updated_at, palette, user_tags, search_tsv, pinned_at
`

type CreateItemParams struct {
	UserID uuid.UUID
	Url    string
	Body   string
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem, arg.UserID, arg.Url, arg.Body)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Title,
		&i.Body,
		&i.LeadImageUrl,
		&i.Summary,
		&i.Tags,
		&i.CardType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Palette,
		&i.UserTags,
		&i.SearchTsv,
		&i.PinnedAt,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :execrows
DELETE FROM items WHERE user_id = $1 AND id = $2
`

type DeleteItemParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteItem(ctx context.Context, arg DeleteItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteItem, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureUser = `-- name: EnsureUser :exec
INSERT INTO users (id) VALUES ($1) ON CONFLICT DO NOTHING
`

func (q *Queries) EnsureUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, ensureUser, id)
	return err
}

const getItem = `-- name: GetItem :one
SELECT id, user_id, url, title, body, lead_image_url, summary, tags, card_type, status, created_at, updated_at, palette, user_tags, search_tsv, pinned_at FROM items WHERE user_id = $1 AND id = $2
`

type GetItemParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) GetItem(ctx context.Context, arg GetItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, getItem, arg.UserID, arg.ID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Title,
		&i.Body,
		&i.LeadImageUrl,
		&i.Summary,
		&i.Tags,
		&i.CardType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Palette,
		&i.UserTags,
		&i.SearchTsv,
		&i.PinnedAt,
	)
	return i, err
}

const listItemURLs = `-- name: ListItemURLs :many
SELECT url FROM items WHERE user_id = $1 AND url <> ''
`

func (q *Queries) ListItemURLs(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listItemURLs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var url string
		if err := rows.Scan(&url); err != nil {
			return nil, err
		}
		items = append(items, url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT id, user_id, url, title, body, lead_image_url, summary, tags, card_type, status, created_at, updated_at, palette, user_tags, search_tsv, pinned_at FROM items WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListItemsParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItems, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
			&i.Body,
			&i.LeadImageUrl,
			&i.Summary,
			&i.Tags,
			&i.CardType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Palette,
			&i.UserTags,
			&i.SearchTsv,
			&i.PinnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsForExport = `-- name: ListItemsForExport :many
SELECT id, user_id, url, title, body, lead_image_url, summary, tags, card_type, status, created_at, updated_at, palette, user_tags, search_tsv, pinned_at FROM items WHERE user_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListItemsForExport(ctx context.Context, userID uuid.UUID) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItemsForExport, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
			&i.Body,
			&i.LeadImageUrl,
			&i.Summary,
			&i.Tags,
			&i.CardType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Palette,
			&i.UserTags,
			&i.SearchTsv,
			&i.PinnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPinned = `-- name: ListPinned :many
SELECT id, user_id, url, title, body, lead_image_url, summary, tags, card_type, status, created_at, updated_at, palette, user_tags, search_tsv, pinned_at FROM items WHERE user_id = $1 AND pinned_at IS NOT NULL ORDER BY pinned_at DESC
`

func (q *Queries) ListPinned(ctx context.Context, userID uuid.UUID) ([]Item, error) {
	rows, err := q.db.Query(ctx, listPinned, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
			&i.Body,
			&i.LeadImageUrl,
			&i.Summary,
			&i.Tags,
			&i.CardType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Palette,
			&i.UserTags,
			&i.SearchTsv,
			&i.PinnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setItemPalette = `-- name: SetItemPalette :exec
UPDATE items SET palette = $3, updated_at = now() WHERE user_id = $1 AND id = $2
`

type SetItemPaletteParams struct {
	UserID  uuid.UUID
	ID      uuid.UUID
	Palette []string
}

func (q *Queries) SetItemPalette(ctx context.Context, arg SetItemPaletteParams) error {
	_, err := q.db.Exec(ctx, setItemPalette, arg.UserID, arg.ID, arg.Palette)
	return err
}

const setItemPinned = `-- name: SetItemPinned :execrows
UPDATE items SET pinned_at = $3, updated_at = now() WHERE user_id = $1 AND id = $2
`

type SetItemPinnedParams struct {
	UserID   uuid.UUID
	ID       uuid.UUID
	PinnedAt pgtype.Timestamptz
}

func (q *Queries) SetItemPinned(ctx context.Context, arg SetItemPinnedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setItemPinned, arg.UserID, arg.ID, arg.PinnedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setItemStatus = `-- name: SetItemStatus :exec
UPDATE items SET status = $3, updated_at = now() WHERE user_id = $1 AND id = $2
`

type SetItemStatusParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetItemStatus(ctx context.Context, arg SetItemStatusParams) error {
	_, err := q.db.Exec(ctx, setItemStatus, arg.UserID, arg.ID, arg.Status)
	return err
}

const setUserTags = `-- name: SetUserTags :execrows
UPDATE items SET user_tags = $3, updated_at = now() WHERE user_id = $1 AND id = $2
`

type SetUserTagsParams struct {
	UserID   uuid.UUID
	ID       uuid.UUID
	UserTags []string
}

func (q *Queries) SetUserTags(ctx context.Context, arg SetUserTagsParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserTags, arg.UserID, arg.ID, arg.UserTags)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateItemEnrichment = `-- name: UpdateItemEnrichment :exec
UPDATE items SET summary = $3, tags = $4, updated_at = now()
WHERE user_id = $1 AND id = $2
`

type UpdateItemEnrichmentParams struct {
	UserID  uuid.UUID
	ID      uuid.UUID
	Summary string
	Tags    []string
}

func (q *Queries) UpdateItemEnrichment(ctx context.Context, arg UpdateItemEnrichmentParams) error {
	_, err := q.db.Exec(ctx, updateItemEnrichment,
		arg.UserID,
		arg.ID,
		arg.Summary,
		arg.Tags,
	)
	return err
}

const updateItemExtraction = `-- name: UpdateItemExtraction :exec
UPDATE items SET title = $3, body = $4, lead_image_url = $5, card_type = $6, updated_at = now()
WHERE user_id = $1 AND id = $2
`

type UpdateItemExtractionParams struct {
	UserID       uuid.UUID
	ID           uuid.UUID
	Title        string
	Body         string
	LeadImageUrl string
	CardType     string
}

func (q *Queries) UpdateItemExtraction(ctx context.Context, arg UpdateItemExtractionParams) error {
	_, err := q.db.Exec(ctx, updateItemExtraction,
		arg.UserID,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.LeadImageUrl,
		arg.CardType,
	)
	return err
}

const upsertEmbedding = `-- name: UpsertEmbedding :exec
INSERT INTO item_embeddings (item_id, user_id, embedding) VALUES ($1, $2, $3)
ON CONFLICT (item_id) DO UPDATE SET embedding = EXCLUDED.embedding
`

type UpsertEmbeddingParams struct {
	ItemID    uuid.UUID
	UserID    uuid.UUID
	Embedding pgvector_go.Vector
}

func (q *Queries) UpsertEmbedding(ctx context.Context, arg UpsertEmbeddingParams) error {
	_, err := q.db.Exec(ctx, upsertEmbedding, arg.ItemID, arg.UserID, arg.Embedding)
	return err
}
