// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: items.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const adoptFeedItems = `-- name: AdoptFeedItems :execrows
UPDATE items SET feed_id = $3 WHERE user_id = $1 AND id = ANY($2::uuid[]) AND feed_id IS NULL
`

type AdoptFeedItemsParams struct {
	UserID  uuid.UUID
	Column2 []uuid.UUID
	FeedID  pgtype.UUID
}

func (q *Queries) AdoptFeedItems(ctx context.Context, arg AdoptFeedItemsParams) (int64, error) {
	result, err := q.db.Exec(ctx, adoptFeedItems, arg.UserID, arg.Column2, arg.FeedID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countDriftCandidates = `-- name: CountDriftCandidates :one
SELECT count(*) FROM items
WHERE user_id = $1 AND status = 'enriched' AND pinned_at IS NULL
  AND (last_drifted_at IS NULL OR last_drifted_at < now() - interval '30 days')
  AND (feed_id IS NULL OR kept_at IS NOT NULL)
`

func (q *Queries) CountDriftCandidates(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDriftCandidates, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFeedItem = `-- name: CreateFeedItem :one
INSERT INTO items (user_id, url, feed_id) VALUES ($1, $2, $3) RETURNING id, user_id, url, title, body, lead_image_url, summary, tags, card_type, status, created_at, updated_at, palette, user_tags, pinned_at, last_drifted_at, search_tsv, page_count, feed_id, kept_at, tagged_location, url_host
`

type CreateFeedItemParams struct {
	UserID uuid.UUID
	Url    string
	FeedID pgtype.UUID
}

func (q *Queries) CreateFeedItem(ctx context.Context, arg CreateFeedItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createFeedItem, arg.UserID, arg.Url, arg.FeedID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Title,
		&i.Body,
		&i.LeadImageUrl,
		&i.Summary,
		&i.Tags,
		&i.CardType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Palette,
		&i.UserTags,
		&i.PinnedAt,
		&i.LastDriftedAt,
		&i.SearchTsv,
		&i.PageCount,
		&i.FeedID,
		&i.KeptAt,
		&i.TaggedLocation,
		&i.UrlHost,
	)
	return i, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO items (user_id, url, body) VALUES ($1, $2, $3) RETURNING id, user_id, url, title, body, lead_image_url, summary, tags, card_type, status, created_at, updated_at, palette, user_tags, pinned_at, last_drifted_at, search_tsv, page_count, feed_id, kept_at, tagged_location, url_host
`

type CreateItemParams struct {
	UserID uuid.UUID
	Url    string
	Body   string
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem, arg.UserID, arg.Url, arg.Body)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Title,
		&i.Body,
		&i.LeadImageUrl,
		&i.Summary,
		&i.Tags,
		&i.CardType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Palette,
		&i.UserTags,
		&i.PinnedAt,
		&i.LastDriftedAt,
		&i.SearchTsv,
		&i.PageCount,
		&i.FeedID,
		&i.KeptAt,
		&i.TaggedLocation,
		&i.UrlHost,
	)
	return i, err
}

const createQuoteItem = `-- name: CreateQuoteItem :one
INSERT INTO items (user_id, body, card_type, url) VALUES ($1, $2, 'quote', '') RETURNING id, user_id, url, title, body, lead_image_url, summary, tags, card_type, status, created_at, updated_at, palette, user_tags, pinned_at, last_drifted_at, search_tsv, page_count, feed_id, kept_at, tagged_location, url_host
`

type CreateQuoteItemParams struct {
	UserID uuid.UUID
	Body   string
}

func (q *Queries) CreateQuoteItem(ctx context.Context, arg CreateQuoteItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createQuoteItem, arg.UserID, arg.Body)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Title,
		&i.Body,
		&i.LeadImageUrl,
		&i.Summary,
		&i.Tags,
		&i.CardType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Palette,
		&i.UserTags,
		&i.PinnedAt,
		&i.LastDriftedAt,
		&i.SearchTsv,
		&i.PageCount,
		&i.FeedID,
		&i.KeptAt,
		&i.TaggedLocation,
		&i.UrlHost,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :execrows
DELETE FROM items WHERE user_id = $1 AND id = $2
`

type DeleteItemParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteItem(ctx context.Context, arg DeleteItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteItem, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const driftAction = `-- name: DriftAction :execrows
UPDATE items
SET last_drifted_at = now(),
    pinned_at = CASE WHEN $3::boolean THEN now() ELSE pinned_at END,
    updated_at = now()
WHERE user_id = $1 AND id = $2
`

type DriftActionParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
	Keep   bool
}

func (q *Queries) DriftAction(ctx context.Context, arg DriftActionParams) (int64, error) {
	result, err := q.db.Exec(ctx, driftAction, arg.UserID, arg.ID, arg.Keep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureUser = `-- name: EnsureUser :exec
INSERT INTO users (id) VALUES ($1) ON CONFLICT DO NOTHING
`

func (q *Queries) EnsureUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, ensureUser, id)
	return err
}

const getItem = `-- name: GetItem :one
SELECT id, user_id, url, title, body, lead_image_url, summary, tags, card_type, status, created_at, updated_at, palette, user_tags, pinned_at, last_drifted_at, search_tsv, page_count, feed_id, kept_at, tagged_location, url_host FROM items WHERE user_id = $1 AND id = $2
`

type GetItemParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) GetItem(ctx context.Context, arg GetItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, getItem, arg.UserID, arg.ID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Title,
		&i.Body,
		&i.LeadImageUrl,
		&i.Summary,
		&i.Tags,
		&i.CardType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Palette,
		&i.UserTags,
		&i.PinnedAt,
		&i.LastDriftedAt,
		&i.SearchTsv,
		&i.PageCount,
		&i.FeedID,
		&i.KeptAt,
		&i.TaggedLocation,
		&i.UrlHost,
	)
	return i, err
}

const getItemByURL = `-- name: GetItemByURL :one
SELECT id, user_id, url, title, body, lead_image_url, summary, tags, card_type, status, created_at, updated_at, palette, user_tags, pinned_at, last_drifted_at, search_tsv, page_count, feed_id, kept_at, tagged_location, url_host FROM items WHERE user_id = $1 AND url = $2 LIMIT 1
`

type GetItemByURLParams struct {
	UserID uuid.UUID
	Url    string
}

func (q *Queries) GetItemByURL(ctx context.Context, arg GetItemByURLParams) (Item, error) {
	row := q.db.QueryRow(ctx, getItemByURL, arg.UserID, arg.Url)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Title,
		&i.Body,
		&i.LeadImageUrl,
		&i.Summary,
		&i.Tags,
		&i.CardType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Palette,
		&i.UserTags,
		&i.PinnedAt,
		&i.LastDriftedAt,
		&i.SearchTsv,
		&i.PageCount,
		&i.FeedID,
		&i.KeptAt,
		&i.TaggedLocation,
		&i.UrlHost,
	)
	return i, err
}

const listDriftCandidates = `-- name: ListDriftCandidates :many
SELECT id, user_id, url, title, body, lead_image_url, summary, tags, card_type, status, created_at, updated_at, palette, user_tags, pinned_at, last_drifted_at, search_tsv, page_count, feed_id, kept_at, tagged_location, url_host FROM items
WHERE user_id = $1 AND status = 'enriched' AND pinned_at IS NULL
  AND (last_drifted_at IS NULL OR last_drifted_at < now() - interval '30 days')
  AND (feed_id IS NULL OR kept_at IS NOT NULL)
ORDER BY last_drifted_at NULLS FIRST, created_at ASC
LIMIT $2
`

type ListDriftCandidatesParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) ListDriftCandidates(ctx context.Context, arg ListDriftCandidatesParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listDriftCandidates, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
			&i.Body,
			&i.LeadImageUrl,
			&i.Summary,
			&i.Tags,
			&i.CardType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Palette,
			&i.UserTags,
			&i.PinnedAt,
			&i.LastDriftedAt,
			&i.SearchTsv,
			&i.PageCount,
			&i.FeedID,
			&i.KeptAt,
			&i.TaggedLocation,
			&i.UrlHost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedItems = `-- name: ListFeedItems :many
SELECT id, user_id, url, title, body, lead_image_url, summary, tags, card_type, status, created_at, updated_at, palette, user_tags, pinned_at, last_drifted_at, search_tsv, page_count, feed_id, kept_at, tagged_location, url_host FROM items
WHERE user_id = $1 AND feed_id IS NOT NULL
  AND ($2::uuid IS NULL OR feed_id = $2)
  AND (
    $3::timestamptz IS NULL
    OR (created_at, id) < ($3::timestamptz, $4::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListFeedItemsParams struct {
	UserID          uuid.UUID
	FilterFeedID    pgtype.UUID
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
	LimitCount      int32
}

func (q *Queries) ListFeedItems(ctx context.Context, arg ListFeedItemsParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listFeedItems,
		arg.UserID,
		arg.FilterFeedID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
			&i.Body,
			&i.LeadImageUrl,
			&i.Summary,
			&i.Tags,
			&i.CardType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Palette,
			&i.UserTags,
			&i.PinnedAt,
			&i.LastDriftedAt,
			&i.SearchTsv,
			&i.PageCount,
			&i.FeedID,
			&i.KeptAt,
			&i.TaggedLocation,
			&i.UrlHost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemURLs = `-- name: ListItemURLs :many
SELECT url FROM items WHERE user_id = $1 AND url <> ''
`

func (q *Queries) ListItemURLs(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listItemURLs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var url string
		if err := rows.Scan(&url); err != nil {
			return nil, err
		}
		items = append(items, url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT id, user_id, url, title, body, lead_image_url, summary, tags, card_type, status, created_at, updated_at, palette, user_tags, pinned_at, last_drifted_at, search_tsv, page_count, feed_id, kept_at, tagged_location, url_host FROM items
WHERE user_id = $1 AND (feed_id IS NULL OR kept_at IS NOT NULL)
  AND (
    $2::timestamptz IS NULL
    OR (created_at, id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListItemsParams struct {
	UserID          uuid.UUID
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
	LimitCount      int32
}

// Keyset (not OFFSET) pagination: the seek is anchored to a row, so a capture
// landing at the head between two requests cannot shift a window and re-serve
// a row the client already holds. id breaks created_at ties.
func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItems,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
			&i.Body,
			&i.LeadImageUrl,
			&i.Summary,
			&i.Tags,
			&i.CardType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Palette,
			&i.UserTags,
			&i.PinnedAt,
			&i.LastDriftedAt,
			&i.SearchTsv,
			&i.PageCount,
			&i.FeedID,
			&i.KeptAt,
			&i.TaggedLocation,
			&i.UrlHost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsAll = `-- name: ListItemsAll :many
SELECT id, user_id, url, title, body, lead_image_url, summary, tags, card_type, status, created_at, updated_at, palette, user_tags, pinned_at, last_drifted_at, search_tsv, page_count, feed_id, kept_at, tagged_location, url_host FROM items
WHERE user_id = $1
ORDER BY created_at DESC LIMIT $2
`

type ListItemsAllParams struct {
	UserID uuid.UUID
	Limit  int32
}

// Same as ListItems but without the Mind predicate: serves the types-only
// Lens rule path, which deliberately spans the feed river so Lenses (and
// Kindle Lens digests) include unkept feed items, matching the text/colour
// rule path (which runs through search and already sees everything).
func (q *Queries) ListItemsAll(ctx context.Context, arg ListItemsAllParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItemsAll, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
			&i.Body,
			&i.LeadImageUrl,
			&i.Summary,
			&i.Tags,
			&i.CardType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Palette,
			&i.UserTags,
			&i.PinnedAt,
			&i.LastDriftedAt,
			&i.SearchTsv,
			&i.PageCount,
			&i.FeedID,
			&i.KeptAt,
			&i.TaggedLocation,
			&i.UrlHost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsForExport = `-- name: ListItemsForExport :many
SELECT id, user_id, url, title, body, lead_image_url, summary, tags, card_type, status, created_at, updated_at, palette, user_tags, pinned_at, last_drifted_at, search_tsv, page_count, feed_id, kept_at, tagged_location, url_host FROM items WHERE user_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListItemsForExport(ctx context.Context, userID uuid.UUID) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItemsForExport, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
			&i.Body,
			&i.LeadImageUrl,
			&i.Summary,
			&i.Tags,
			&i.CardType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Palette,
			&i.UserTags,
			&i.PinnedAt,
			&i.LastDriftedAt,
			&i.SearchTsv,
			&i.PageCount,
			&i.FeedID,
			&i.KeptAt,
			&i.TaggedLocation,
			&i.UrlHost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPinned = `-- name: ListPinned :many
SELECT id, user_id, url, title, body, lead_image_url, summary, tags, card_type, status, created_at, updated_at, palette, user_tags, pinned_at, last_drifted_at, search_tsv, page_count, feed_id, kept_at, tagged_location, url_host FROM items WHERE user_id = $1 AND pinned_at IS NOT NULL ORDER BY pinned_at DESC
`

func (q *Queries) ListPinned(ctx context.Context, userID uuid.UUID) ([]Item, error) {
	rows, err := q.db.Query(ctx, listPinned, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
			&i.Body,
			&i.LeadImageUrl,
			&i.Summary,
			&i.Tags,
			&i.CardType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Palette,
			&i.UserTags,
			&i.PinnedAt,
			&i.LastDriftedAt,
			&i.SearchTsv,
			&i.PageCount,
			&i.FeedID,
			&i.KeptAt,
			&i.TaggedLocation,
			&i.UrlHost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setItemKept = `-- name: SetItemKept :execrows
UPDATE items SET kept_at = $3, updated_at = now() WHERE user_id = $1 AND id = $2
`

type SetItemKeptParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
	KeptAt pgtype.Timestamptz
}

func (q *Queries) SetItemKept(ctx context.Context, arg SetItemKeptParams) (int64, error) {
	result, err := q.db.Exec(ctx, setItemKept, arg.UserID, arg.ID, arg.KeptAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setItemPageCount = `-- name: SetItemPageCount :exec
UPDATE items SET page_count = $3 WHERE user_id = $1 AND id = $2
`

type SetItemPageCountParams struct {
	UserID    uuid.UUID
	ID        uuid.UUID
	PageCount pgtype.Int4
}

func (q *Queries) SetItemPageCount(ctx context.Context, arg SetItemPageCountParams) error {
	_, err := q.db.Exec(ctx, setItemPageCount, arg.UserID, arg.ID, arg.PageCount)
	return err
}

const setItemPalette = `-- name: SetItemPalette :exec
UPDATE items SET palette = $3, updated_at = now() WHERE user_id = $1 AND id = $2
`

type SetItemPaletteParams struct {
	UserID  uuid.UUID
	ID      uuid.UUID
	Palette []string
}

func (q *Queries) SetItemPalette(ctx context.Context, arg SetItemPaletteParams) error {
	_, err := q.db.Exec(ctx, setItemPalette, arg.UserID, arg.ID, arg.Palette)
	return err
}

const setItemPinned = `-- name: SetItemPinned :execrows
UPDATE items SET pinned_at = $3, updated_at = now() WHERE user_id = $1 AND id = $2
`

type SetItemPinnedParams struct {
	UserID   uuid.UUID
	ID       uuid.UUID
	PinnedAt pgtype.Timestamptz
}

func (q *Queries) SetItemPinned(ctx context.Context, arg SetItemPinnedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setItemPinned, arg.UserID, arg.ID, arg.PinnedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setItemStatus = `-- name: SetItemStatus :exec
UPDATE items SET status = $3, updated_at = now() WHERE user_id = $1 AND id = $2
`

type SetItemStatusParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetItemStatus(ctx context.Context, arg SetItemStatusParams) error {
	_, err := q.db.Exec(ctx, setItemStatus, arg.UserID, arg.ID, arg.Status)
	return err
}

const setItemURL = `-- name: SetItemURL :exec
UPDATE items SET url = $3 WHERE user_id = $1 AND id = $2
`

type SetItemURLParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
	Url    string
}

func (q *Queries) SetItemURL(ctx context.Context, arg SetItemURLParams) error {
	_, err := q.db.Exec(ctx, setItemURL, arg.UserID, arg.ID, arg.Url)
	return err
}

const setUserTags = `-- name: SetUserTags :execrows
UPDATE items SET user_tags = $3, updated_at = now() WHERE user_id = $1 AND id = $2
`

type SetUserTagsParams struct {
	UserID   uuid.UUID
	ID       uuid.UUID
	UserTags []string
}

func (q *Queries) SetUserTags(ctx context.Context, arg SetUserTagsParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserTags, arg.UserID, arg.ID, arg.UserTags)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateItemEnrichment = `-- name: UpdateItemEnrichment :exec
UPDATE items SET summary = $3, tags = $4, updated_at = now()
WHERE user_id = $1 AND id = $2
`

type UpdateItemEnrichmentParams struct {
	UserID  uuid.UUID
	ID      uuid.UUID
	Summary string
	Tags    []string
}

func (q *Queries) UpdateItemEnrichment(ctx context.Context, arg UpdateItemEnrichmentParams) error {
	_, err := q.db.Exec(ctx, updateItemEnrichment,
		arg.UserID,
		arg.ID,
		arg.Summary,
		arg.Tags,
	)
	return err
}

const updateItemExtraction = `-- name: UpdateItemExtraction :exec
UPDATE items SET title = $3, body = $4, lead_image_url = $5, card_type = $6, tagged_location = $7, updated_at = now()
WHERE user_id = $1 AND id = $2
`

type UpdateItemExtractionParams struct {
	UserID         uuid.UUID
	ID             uuid.UUID
	Title          string
	Body           string
	LeadImageUrl   string
	CardType       string
	TaggedLocation string
}

func (q *Queries) UpdateItemExtraction(ctx context.Context, arg UpdateItemExtractionParams) error {
	_, err := q.db.Exec(ctx, updateItemExtraction,
		arg.UserID,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.LeadImageUrl,
		arg.CardType,
		arg.TaggedLocation,
	)
	return err
}

const upsertEmbedding = `-- name: UpsertEmbedding :exec
INSERT INTO item_embeddings (item_id, user_id, embedding) VALUES ($1, $2, $3)
ON CONFLICT (item_id) DO UPDATE SET embedding = EXCLUDED.embedding
`

type UpsertEmbeddingParams struct {
	ItemID    uuid.UUID
	UserID    uuid.UUID
	Embedding pgvector_go.Vector
}

func (q *Queries) UpsertEmbedding(ctx context.Context, arg UpsertEmbeddingParams) error {
	_, err := q.db.Exec(ctx, upsertEmbedding, arg.ItemID, arg.UserID, arg.Embedding)
	return err
}
