// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: jev.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addJevDismissedTag = `-- name: AddJevDismissedTag :execrows
UPDATE jev_decisions
SET dismissed_tags = (
    SELECT COALESCE(array_agg(DISTINCT t), '{}')
    FROM unnest(dismissed_tags || ARRAY[$1::text]) AS t
)
WHERE user_id = $2 AND id = $3
`

type AddJevDismissedTagParams struct {
	Tag    string
	UserID uuid.UUID
	ID     int64
}

// Append a dismissed suggestion tag (idempotent via DISTINCT).
func (q *Queries) AddJevDismissedTag(ctx context.Context, arg AddJevDismissedTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, addJevDismissedTag, arg.Tag, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJevCaptureDecision = `-- name: GetJevCaptureDecision :one
SELECT id, user_id, item_id, surface, model, questions_v, answers, action,
       user_verdict, latency_ms, input_tokens, created_at,
       applied_tags, suggested_tags, dismissed_tags
FROM jev_decisions
WHERE user_id = $1 AND item_id = $2 AND surface = 'capture'
LIMIT 1
`

type GetJevCaptureDecisionParams struct {
	UserID uuid.UUID
	ItemID pgtype.UUID
}

func (q *Queries) GetJevCaptureDecision(ctx context.Context, arg GetJevCaptureDecisionParams) (JevDecision, error) {
	row := q.db.QueryRow(ctx, getJevCaptureDecision, arg.UserID, arg.ItemID)
	var i JevDecision
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.Surface,
		&i.Model,
		&i.QuestionsV,
		&i.Answers,
		&i.Action,
		&i.UserVerdict,
		&i.LatencyMs,
		&i.InputTokens,
		&i.CreatedAt,
		&i.AppliedTags,
		&i.SuggestedTags,
		&i.DismissedTags,
	)
	return i, err
}

const insertJevDecision = `-- name: InsertJevDecision :one
INSERT INTO jev_decisions (
    user_id, item_id, surface, model, questions_v, answers, action,
    latency_ms, input_tokens, applied_tags, suggested_tags, dismissed_tags
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, user_id, item_id, surface, model, questions_v, answers, action,
          user_verdict, latency_ms, input_tokens, created_at,
          applied_tags, suggested_tags, dismissed_tags
`

type InsertJevDecisionParams struct {
	UserID        uuid.UUID
	ItemID        pgtype.UUID
	Surface       string
	Model         string
	QuestionsV    string
	Answers       []byte
	Action        string
	LatencyMs     pgtype.Int4
	InputTokens   pgtype.Int4
	AppliedTags   []string
	SuggestedTags []string
	DismissedTags []string
}

func (q *Queries) InsertJevDecision(ctx context.Context, arg InsertJevDecisionParams) (JevDecision, error) {
	row := q.db.QueryRow(ctx, insertJevDecision,
		arg.UserID,
		arg.ItemID,
		arg.Surface,
		arg.Model,
		arg.QuestionsV,
		arg.Answers,
		arg.Action,
		arg.LatencyMs,
		arg.InputTokens,
		arg.AppliedTags,
		arg.SuggestedTags,
		arg.DismissedTags,
	)
	var i JevDecision
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.Surface,
		&i.Model,
		&i.QuestionsV,
		&i.Answers,
		&i.Action,
		&i.UserVerdict,
		&i.LatencyMs,
		&i.InputTokens,
		&i.CreatedAt,
		&i.AppliedTags,
		&i.SuggestedTags,
		&i.DismissedTags,
	)
	return i, err
}

const listUserTagVocabulary = `-- name: ListUserTagVocabulary :many
SELECT DISTINCT unnest(user_tags)::text AS tag
FROM items
WHERE user_id = $1 AND cardinality(user_tags) > 0
ORDER BY tag
`

// Distinct user_tags across the caller's library, ordered for stable question ids.
func (q *Queries) ListUserTagVocabulary(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserTagVocabulary, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setJevUserVerdict = `-- name: SetJevUserVerdict :execrows
UPDATE jev_decisions
SET user_verdict = $1
WHERE user_id = $2 AND id = $3
`

type SetJevUserVerdictParams struct {
	UserVerdict pgtype.Text
	UserID      uuid.UUID
	ID          int64
}

func (q *Queries) SetJevUserVerdict(ctx context.Context, arg SetJevUserVerdictParams) (int64, error) {
	result, err := q.db.Exec(ctx, setJevUserVerdict, arg.UserVerdict, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
