// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: lenses.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createLens = `-- name: CreateLens :one
INSERT INTO lenses (user_id, name, rule) VALUES ($1, $2, $3) RETURNING id, user_id, name, rule, created_at, updated_at
`

type CreateLensParams struct {
	UserID uuid.UUID
	Name   string
	Rule   []byte
}

func (q *Queries) CreateLens(ctx context.Context, arg CreateLensParams) (Lense, error) {
	row := q.db.QueryRow(ctx, createLens, arg.UserID, arg.Name, arg.Rule)
	var i Lense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Rule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLens = `-- name: DeleteLens :execrows
DELETE FROM lenses WHERE user_id = $1 AND id = $2
`

type DeleteLensParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteLens(ctx context.Context, arg DeleteLensParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLens, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLens = `-- name: GetLens :one
SELECT id, user_id, name, rule, created_at, updated_at FROM lenses WHERE user_id = $1 AND id = $2
`

type GetLensParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) GetLens(ctx context.Context, arg GetLensParams) (Lense, error) {
	row := q.db.QueryRow(ctx, getLens, arg.UserID, arg.ID)
	var i Lense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Rule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLenses = `-- name: ListLenses :many
SELECT id, user_id, name, rule, created_at, updated_at FROM lenses WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListLenses(ctx context.Context, userID uuid.UUID) ([]Lense, error) {
	rows, err := q.db.Query(ctx, listLenses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lense
	for rows.Next() {
		var i Lense
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Rule,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLens = `-- name: UpdateLens :one
UPDATE lenses SET name = $3, rule = $4, updated_at = now()
WHERE user_id = $1 AND id = $2 RETURNING id, user_id, name, rule, created_at, updated_at
`

type UpdateLensParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
	Name   string
	Rule   []byte
}

func (q *Queries) UpdateLens(ctx context.Context, arg UpdateLensParams) (Lense, error) {
	row := q.db.QueryRow(ctx, updateLens,
		arg.UserID,
		arg.ID,
		arg.Name,
		arg.Rule,
	)
	var i Lense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Rule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
