// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: links.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createLink = `-- name: CreateLink :execrows
INSERT INTO links (user_id, a_item, b_item)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type CreateLinkParams struct {
	UserID uuid.UUID
	AItem  uuid.UUID
	BItem  uuid.UUID
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, createLink, arg.UserID, arg.AItem, arg.BItem)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLink = `-- name: DeleteLink :execrows
DELETE FROM links WHERE user_id = $1 AND a_item = $2 AND b_item = $3
`

type DeleteLinkParams struct {
	UserID uuid.UUID
	AItem  uuid.UUID
	BItem  uuid.UUID
}

func (q *Queries) DeleteLink(ctx context.Context, arg DeleteLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLink, arg.UserID, arg.AItem, arg.BItem)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listLinkedItems = `-- name: ListLinkedItems :many
SELECT i.id, i.user_id, i.url, i.title, i.body, i.lead_image_url, i.summary, i.tags, i.card_type, i.status, i.created_at, i.updated_at, i.palette, i.user_tags, i.pinned_at, i.last_drifted_at, i.search_tsv, i.page_count, i.feed_id, i.kept_at, i.tagged_location FROM links l
JOIN items i ON i.id = CASE WHEN l.a_item = $2 THEN l.b_item ELSE l.a_item END
WHERE l.user_id = $1 AND ($2 IN (l.a_item, l.b_item))
ORDER BY l.created_at DESC
`

type ListLinkedItemsParams struct {
	UserID uuid.UUID
	AItem  uuid.UUID
}

func (q *Queries) ListLinkedItems(ctx context.Context, arg ListLinkedItemsParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listLinkedItems, arg.UserID, arg.AItem)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
			&i.Body,
			&i.LeadImageUrl,
			&i.Summary,
			&i.Tags,
			&i.CardType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Palette,
			&i.UserTags,
			&i.PinnedAt,
			&i.LastDriftedAt,
			&i.SearchTsv,
			&i.PageCount,
			&i.FeedID,
			&i.KeptAt,
			&i.TaggedLocation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
