// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type Asset struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	ItemID           pgtype.UUID
	ContentType      string
	ByteSize         int64
	OriginalFilename string
	CreatedAt        pgtype.Timestamptz
}

type Item struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Url          string
	Title        string
	Body         string
	LeadImageUrl string
	Summary      string
	Tags         []string
	CardType     string
	Status       string
	SearchTsv    interface{}
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type ItemEmbedding struct {
	ItemID    uuid.UUID
	UserID    uuid.UUID
	Embedding pgvector_go.Vector
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
}
