// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: places.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteItemPlace = `-- name: DeleteItemPlace :execrows
DELETE FROM item_places WHERE user_id = $1 AND item_id = $2 AND id = $3
`

type DeleteItemPlaceParams struct {
	UserID uuid.UUID
	ItemID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteItemPlace(ctx context.Context, arg DeleteItemPlaceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteItemPlace, arg.UserID, arg.ItemID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteItemPlaces = `-- name: DeleteItemPlaces :exec
DELETE FROM item_places WHERE user_id = $1 AND item_id = $2
`

type DeleteItemPlacesParams struct {
	UserID uuid.UUID
	ItemID uuid.UUID
}

func (q *Queries) DeleteItemPlaces(ctx context.Context, arg DeleteItemPlacesParams) error {
	_, err := q.db.Exec(ctx, deleteItemPlaces, arg.UserID, arg.ItemID)
	return err
}

const insertItemPlace = `-- name: InsertItemPlace :exec
INSERT INTO item_places (user_id, item_id, name, hint, address, lat, lng, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertItemPlaceParams struct {
	UserID  uuid.UUID
	ItemID  uuid.UUID
	Name    string
	Hint    string
	Address string
	Lat     pgtype.Float8
	Lng     pgtype.Float8
	Source  string
}

func (q *Queries) InsertItemPlace(ctx context.Context, arg InsertItemPlaceParams) error {
	_, err := q.db.Exec(ctx, insertItemPlace,
		arg.UserID,
		arg.ItemID,
		arg.Name,
		arg.Hint,
		arg.Address,
		arg.Lat,
		arg.Lng,
		arg.Source,
	)
	return err
}

const listItemPlaces = `-- name: ListItemPlaces :many
SELECT id, user_id, item_id, name, hint, address, lat, lng, source, created_at FROM item_places WHERE user_id = $1 AND item_id = $2 ORDER BY created_at, name
`

type ListItemPlacesParams struct {
	UserID uuid.UUID
	ItemID uuid.UUID
}

func (q *Queries) ListItemPlaces(ctx context.Context, arg ListItemPlacesParams) ([]ItemPlace, error) {
	rows, err := q.db.Query(ctx, listItemPlaces, arg.UserID, arg.ItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemPlace
	for rows.Next() {
		var i ItemPlace
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ItemID,
			&i.Name,
			&i.Hint,
			&i.Address,
			&i.Lat,
			&i.Lng,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaces = `-- name: ListPlaces :many
SELECT p.id, p.name, p.hint, p.address, p.lat, p.lng, p.source,
       i.id AS item_id, i.title AS item_title, i.card_type AS item_card_type
FROM item_places p
JOIN items i ON i.id = p.item_id AND i.user_id = p.user_id
WHERE p.user_id = $1
ORDER BY i.created_at DESC, p.name
`

type ListPlacesRow struct {
	ID           uuid.UUID
	Name         string
	Hint         string
	Address      string
	Lat          pgtype.Float8
	Lng          pgtype.Float8
	Source       string
	ItemID       uuid.UUID
	ItemTitle    string
	ItemCardType string
}

func (q *Queries) ListPlaces(ctx context.Context, userID uuid.UUID) ([]ListPlacesRow, error) {
	rows, err := q.db.Query(ctx, listPlaces, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlacesRow
	for rows.Next() {
		var i ListPlacesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hint,
			&i.Address,
			&i.Lat,
			&i.Lng,
			&i.Source,
			&i.ItemID,
			&i.ItemTitle,
			&i.ItemCardType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
