// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: search.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const listItemsWithPalette = `-- name: ListItemsWithPalette :many
SELECT id, user_id, url, title, body, lead_image_url, summary, tags, card_type, status, created_at, updated_at, palette, user_tags, search_tsv FROM items WHERE user_id = $1 AND cardinality(palette) > 0
`

func (q *Queries) ListItemsWithPalette(ctx context.Context, userID uuid.UUID) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItemsWithPalette, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
			&i.Body,
			&i.LeadImageUrl,
			&i.Summary,
			&i.Tags,
			&i.CardType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Palette,
			&i.UserTags,
			&i.SearchTsv,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchFTS = `-- name: SearchFTS :many
SELECT id, user_id, url, title, body, lead_image_url, summary, tags, card_type, status, created_at, updated_at, palette, user_tags, search_tsv, ts_rank(search_tsv, websearch_to_tsquery('english', $2))::float8 AS rank
FROM items
WHERE user_id = $1 AND search_tsv @@ websearch_to_tsquery('english', $2)
ORDER BY rank DESC LIMIT $3
`

type SearchFTSParams struct {
	UserID             uuid.UUID
	WebsearchToTsquery string
	Limit              int32
}

type SearchFTSRow struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Url          string
	Title        string
	Body         string
	LeadImageUrl string
	Summary      string
	Tags         []string
	CardType     string
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Palette      []string
	UserTags     []string
	SearchTsv    interface{}
	Rank         float64
}

func (q *Queries) SearchFTS(ctx context.Context, arg SearchFTSParams) ([]SearchFTSRow, error) {
	rows, err := q.db.Query(ctx, searchFTS, arg.UserID, arg.WebsearchToTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchFTSRow
	for rows.Next() {
		var i SearchFTSRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
			&i.Body,
			&i.LeadImageUrl,
			&i.Summary,
			&i.Tags,
			&i.CardType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Palette,
			&i.UserTags,
			&i.SearchTsv,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchVector = `-- name: SearchVector :many
SELECT i.id, i.user_id, i.url, i.title, i.body, i.lead_image_url, i.summary, i.tags, i.card_type, i.status, i.created_at, i.updated_at, i.palette, i.user_tags, i.search_tsv, (1 - (e.embedding <=> $2))::float8 AS similarity
FROM item_embeddings e JOIN items i ON i.id = e.item_id
WHERE e.user_id = $1
ORDER BY e.embedding <=> $2 LIMIT $3
`

type SearchVectorParams struct {
	UserID    uuid.UUID
	Embedding pgvector_go.Vector
	Limit     int32
}

type SearchVectorRow struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Url          string
	Title        string
	Body         string
	LeadImageUrl string
	Summary      string
	Tags         []string
	CardType     string
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Palette      []string
	UserTags     []string
	SearchTsv    interface{}
	Similarity   float64
}

func (q *Queries) SearchVector(ctx context.Context, arg SearchVectorParams) ([]SearchVectorRow, error) {
	rows, err := q.db.Query(ctx, searchVector, arg.UserID, arg.Embedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchVectorRow
	for rows.Next() {
		var i SearchVectorRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
			&i.Body,
			&i.LeadImageUrl,
			&i.Summary,
			&i.Tags,
			&i.CardType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Palette,
			&i.UserTags,
			&i.SearchTsv,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
