// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: settings.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteUserSetting = `-- name: DeleteUserSetting :execrows
DELETE FROM user_settings WHERE user_id = $1 AND key = $2
`

type DeleteUserSettingParams struct {
	UserID uuid.UUID
	Key    string
}

func (q *Queries) DeleteUserSetting(ctx context.Context, arg DeleteUserSettingParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserSetting, arg.UserID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserSetting = `-- name: GetUserSetting :one
SELECT value FROM user_settings WHERE user_id = $1 AND key = $2
`

type GetUserSettingParams struct {
	UserID uuid.UUID
	Key    string
}

func (q *Queries) GetUserSetting(ctx context.Context, arg GetUserSettingParams) (string, error) {
	row := q.db.QueryRow(ctx, getUserSetting, arg.UserID, arg.Key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const listUserSettings = `-- name: ListUserSettings :many
SELECT key, value FROM user_settings WHERE user_id = $1
`

type ListUserSettingsRow struct {
	Key   string
	Value string
}

func (q *Queries) ListUserSettings(ctx context.Context, userID uuid.UUID) ([]ListUserSettingsRow, error) {
	rows, err := q.db.Query(ctx, listUserSettings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserSettingsRow
	for rows.Next() {
		var i ListUserSettingsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithAIAssisted = `-- name: ListUsersWithAIAssisted :many
SELECT user_id FROM user_settings
WHERE key = 'ai_assisted_organisation' AND lower(trim(value)) = 'true'
`

// Users who opted into AI-assisted organisation (Jev capture / rerank / Drift).
func (q *Queries) ListUsersWithAIAssisted(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUsersWithAIAssisted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserSetting = `-- name: UpsertUserSetting :exec
INSERT INTO user_settings (user_id, key, value) VALUES ($1, $2, $3)
ON CONFLICT (user_id, key) DO UPDATE SET value = EXCLUDED.value, updated_at = now()
`

type UpsertUserSettingParams struct {
	UserID uuid.UUID
	Key    string
	Value  string
}

func (q *Queries) UpsertUserSetting(ctx context.Context, arg UpsertUserSettingParams) error {
	_, err := q.db.Exec(ctx, upsertUserSetting, arg.UserID, arg.Key, arg.Value)
	return err
}
